import React, { useEffect, useState } from 'react';
import { AlertCircle, Box, CheckCircle2, Layers, RefreshCw } from 'lucide-react';
import { ApiClient } from '../../api/client';
import { useApp } from '../../context/AppContext';
import { Button, Card } from '../ui/DesignSystem';

export const ClientPackagesList: React.FC = () => {
  const { addToast } = useApp();
  const [packages, setPackages] = useState<any[]>([]); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = async () => { setLoading(true); const result = await ApiClient.getInternationalPackages(); if (result.success) { setPackages(result.packages || []); setError(''); } else setError(result.error); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const consolidate = async () => { if (selectedIds.length < 2) return; setBusy(true); const result = await ApiClient.consolidateInternationalPackages(selectedIds, 'Solicitud desde portal de cliente'); setBusy(false); if (!result.success) { addToast('error', 'Consolidación rechazada', result.error); return; } addToast('success', 'Consolidación guardada', `Master ${result.masterTracking} confirmado por GoPaq.`); setSelectedIds([]); await load(); };
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 text-xl font-extrabold"><Layers className="h-6 w-6 text-indigo-600" />Mis paquetes internacionales</h2><p className="mt-1 text-xs text-slate-500">Paquetes y consolidaciones consultados y guardados en el motor internacional.</p></div><div className="flex gap-2"><Button variant="secondary" size="sm" icon={<RefreshCw className="h-4 w-4" />} onClick={() => void load()}>Actualizar</Button><Button variant="primary" size="md" disabled={selectedIds.length < 2 || busy} onClick={() => void consolidate()}>{busy ? 'Guardando…' : `Solicitar consolidación (${selectedIds.length})`}</Button></div></div>{error && <div className="flex items-start gap-2 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><AlertCircle className="h-4 w-4 shrink-0" />{error}</div>}{loading ? <Card><p className="text-sm text-slate-500">Cargando paquetes desde GoPaq…</p></Card> : !packages.length ? <Card><div className="py-8 text-center"><Box className="mx-auto h-8 w-8 text-slate-400" /><p className="mt-2 text-sm text-slate-500">No hay paquetes internacionales registrados.</p></div></Card> : <div className="grid grid-cols-1 gap-5 md:grid-cols-3">{packages.map((pkg) => { const selected = selectedIds.includes(pkg.id); return <Card key={pkg.id} className={selected ? 'ring-2 ring-indigo-500' : ''}><label className="flex items-start gap-3"><input type="checkbox" checked={selected} disabled={pkg.status === 'consolidated'} onChange={() => setSelectedIds((current) => current.includes(pkg.id) ? current.filter((id) => id !== pkg.id) : [...current, pkg.id])} className="mt-1" /><span><span className="block text-sm font-bold">{pkg.merchant_name || 'Comercio no indicado'}</span><span className="mt-1 block font-mono text-xs text-indigo-600">{pkg.tracking_number}</span></span></label><div className="mt-4 space-y-2 border-t border-slate-100 pt-4 text-xs dark:border-slate-800"><p>{pkg.description}</p><p className="text-slate-500">{pkg.weight_lbs} lb · USD {pkg.declared_value_usd} · Estado: {pkg.status}</p>{pkg.status === 'consolidated' && <p className="flex items-center gap-1 font-bold text-emerald-700"><CheckCircle2 className="h-3.5 w-3.5" />Consolidado</p>}</div></Card>; })}</div>}</div>;
};
