import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, Clock, CreditCard, DollarSign, RefreshCw } from 'lucide-react';
import { ApiClient } from '../../api/client';
import { useApp } from '../../context/AppContext';
import { Button, Card, MetricCard } from '../ui/DesignSystem';

const statusLabel: Record<string, string> = { pending_collection: 'Pendiente de cobro', collected_driver: 'Cobrado por driver', received_branch: 'Recibido en sucursal', reconciled: 'Conciliado', settled_merchant: 'Liquidado' };
export const ClientBilling: React.FC = () => {
  const { formatMoney } = useApp(); const [transactions, setTransactions] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); const result = await ApiClient.getCodLedger(); if (result.success) { setTransactions(result.transactions || []); setError(''); } else setError(result.error); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const total = useMemo(() => transactions.reduce((sum, tx) => sum + Number(tx.amount || 0), 0), [transactions]); const pending = useMemo(() => transactions.filter((tx) => ['pending_collection', 'collected_driver', 'received_branch', 'reconciled'].includes(tx.status)).reduce((sum, tx) => sum + Number(tx.amount || 0), 0), [transactions]); const settled = useMemo(() => transactions.filter((tx) => tx.status === 'settled_merchant').reduce((sum, tx) => sum + Number(tx.amount || 0), 0), [transactions]);
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 text-xl font-extrabold"><CreditCard className="h-6 w-6 text-indigo-600" />Estado de cuenta COD</h2><p className="mt-1 text-xs text-slate-500">Montos consultados del libro financiero de tu cuenta. No se muestran facturas ni liquidaciones que no existan en el servidor.</p></div><Button variant="secondary" size="sm" icon={<RefreshCw className="h-4 w-4" />} onClick={() => void load()}>Actualizar</Button></div>{error && <div className="flex items-start gap-2 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><AlertCircle className="h-4 w-4 shrink-0" />{error}</div>}<div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><MetricCard title="COD en curso" value={formatMoney(pending)} subtitle="Pendiente de liquidación" icon={<DollarSign className="h-5 w-5" />} accent="amber" /><MetricCard title="Liquidado" value={formatMoney(settled)} subtitle="Estado final registrado" icon={<CheckCircle2 className="h-5 w-5" />} accent="emerald" /><MetricCard title="Movimientos" value={String(transactions.length)} subtitle={`Total histórico: ${formatMoney(total)}`} icon={<Clock className="h-5 w-5" />} accent="indigo" /></div><Card className="overflow-hidden p-0"><div className="border-b border-slate-200 p-4 text-sm font-bold dark:border-slate-800">Movimientos COD de tu organización</div>{loading ? <p className="p-6 text-sm text-slate-500">Consultando libro financiero…</p> : !transactions.length ? <p className="p-6 text-sm text-slate-500">No hay movimientos COD registrados.</p> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{transactions.map((tx) => <div key={tx.id} className="flex flex-wrap items-center justify-between gap-3 p-4 text-xs"><div><p className="font-mono font-bold">{tx.tracking_number || tx.shipment_id}</p><p className="mt-1 text-slate-500">{statusLabel[tx.status] || tx.status}</p></div><span className="font-mono font-bold text-emerald-700">{formatMoney(Number(tx.amount || 0), tx.currency)}</span></div>)}</div>}</Card></div>;
};
