import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, protectedProcedure, router } from "./_core/trpc";
import { addPackageToConsolidationForUser, advanceConsolidationForUser, advanceManifestForUser, createIncidentForUser, appendAuditLog, collectPaymentForUser, createShipmentServiceForUser, closeCashSessionForUser, issueInvoiceForUser, appendShipmentEvent, canUser, assignRouteForUser, createApiKeyForUser, createConsolidationForUser, createManifestForUser, createPickupForUser, createRouteForUser, createRouteStopForUser, isRouteAssignedToUser, isRouteStopAssignedToUser, isActiveRouteStopAssignedToUser, isShipmentOnAssignedRouteForUser, createShipmentForUser, cancelShipmentForUser, createPackageForUser, createWarehouseForUser, confirmShipmentDeliveryForUser, getActiveTariffForOrganization, getOrganizationForUser, getOrganizationBySlug, getPublicTrackingByCode, listApiKeysForUser, listApiRequestLogsForUser, listAuditLogsForUser, listBranchesForUser, listConsolidationsForUser, listDriversForUser, listIncidentsForUser, listInventoryMovementsForUser, listPackagesForUser, listShipmentDocumentsForUser, listEventsForUser, listManifestsForUser, listPickupsForUser, listRouteExpensesForUser, createRouteExpenseForUser, reviewRouteExpenseForUser, listAssignedRouteStopsForUser, listAssignedRoutesForUser, listRouteStopsForUser, listRoutesForUser, listShipmentsForUser, listTrackingPointsForUser, listWarehousesForUser, listDeliveryAttemptsForUser, listCashSessionsForUser, listInvoicesForUser, listPaymentsForUser, listShipmentServicesForUser, recordDeliveryAttemptForUser, recordInventoryMovementForUser, recordTrackingPoint, revokeApiKeyForUser, resolveIncidentForUser, scanPackageForUser, updateAssignedRouteForUser, updateRouteStopForUser, openCashSessionForUser, updateShipmentForUser, updateShipmentServiceForUser, updatePackageForUser, updateWarehouseForUser, listMembershipsForUser, listRolePermissionsForUser, grantRolePermissionForUser, revokeRolePermissionForUser, refundPaymentForUser, repackPackageForUser, splitPackageForUser, listTariffZonesForUser, createTariffZoneForUser, listTariffsForUser, createTariffForUser, updateMembershipScopeForUser, updateOrganizationProfileForUser, uploadShipmentDocumentForUser, getCustomerProfileForUser, upsertCustomerProfileForUser, listCustomerAddressesForUser, createCustomerAddressForUser, updateCustomerAddressForUser, listCustomerContactsForUser, createCustomerContactForUser, updateCustomerContactForUser, listSupportTicketsForUser, createSupportTicketForUser, updateSupportTicketForUser, listOrganizationsForSuperAdmin, updateOrganizationStatusForSuperAdmin, listWebhookEndpointsForUser, createWebhookEndpointForUser, dispatchWebhookForUser, listWebhookDeliveriesForUser, updatePickupStatusForUser } from "./db";
import { invokeLLM } from "./_core/llm";
import { AGENT_ACTION_TYPES, enforceAgentApproval } from "./agentPolicy";
import { calculateQuote } from "./tariffEngine";
import { buildTrackingAuditMetadata, trackingResourceId } from "./trackingAudit";
import { buildDopTariffInput } from "./tariffCatalog";

export const appRouter = router({
  superAdmin: router({
    organizations: protectedProcedure.query(async ({ ctx }) => {
      const result = await listOrganizationsForSuperAdmin(ctx.user.id);
      if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "Se requiere rol Super Admin" });
      return result;
    }),
    updateOrganizationStatus: protectedProcedure.input(z.object({ organizationId: z.number().int().positive(), status: z.enum(["trial", "active", "suspended"]) })).mutation(async ({ ctx, input }) => {
      const result = await updateOrganizationStatusForSuperAdmin(ctx.user.id, input.organizationId, input.status);
      if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "No autorizado o organización inexistente" });
      await appendAuditLog({ organizationId: input.organizationId, actorUserId: ctx.user.id, category: "security", action: "super_admin.organization.status_updated", resourceType: "organization", resourceId: String(input.organizationId), metadata: { previousStatus: result.before.status, nextStatus: result.after?.status ?? input.status } });
      return result.after;
    }),
  }),
  webhooks: router({
    list: protectedProcedure.query(async ({ ctx }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "webhooks", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de webhooks no disponible" });
      return listWebhookEndpointsForUser(ctx.user.id);
    }),
    create: protectedProcedure.input(z.object({ name: z.string().trim().min(2).max(160), url: z.string().url(), secret: z.string().min(16).max(200), subscribedEvents: z.array(z.string().trim().min(3).max(120)).min(1).max(30) })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "webhooks", "configure"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de configuración de webhooks no disponible" });
      const result = await createWebhookEndpointForUser(ctx.user.id, input);
      if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "Destino inválido o secreto no seguro" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "webhook.endpoint.created", resourceType: "webhook_endpoint", resourceId: String(result.id), metadata: { name: result.name, url: result.url, subscribedEvents: result.subscribedEvents } });
      return result;
    }),
    deliveries: protectedProcedure.input(z.object({ endpointId: z.number().int().positive().optional(), eventType: z.string().trim().min(3).max(120).optional(), status: z.enum(["pending", "delivered", "failed", "exhausted"]).optional() }).optional()).query(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "webhooks", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de consulta de entregas no disponible" });
      return listWebhookDeliveriesForUser(ctx.user.id, input);
    }),
    dispatch: protectedProcedure.input(z.object({ endpointId: z.number().int().positive(), eventType: z.string().trim().min(3).max(120), data: z.record(z.string(), z.unknown()) })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "webhooks", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de entrega de webhooks no disponible" });
      const result = await dispatchWebhookForUser(ctx.user.id, input);
      if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "Destino inexistente, inactivo o no suscrito al evento" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "webhook.delivery.attempted", resourceType: "webhook_delivery", resourceId: String(result.deliveryId), metadata: result });
      return result;
    }),
  }),
  organization: router({
    updateProfile: protectedProcedure.input(z.object({ country: z.string().min(2).max(80), language: z.string().min(2).max(8), currency: z.string().min(3).max(8), timezone: z.string().min(3).max(80), activeServices: z.array(z.string().min(2).max(48)).max(20) })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "organization", "configure"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de configuración de organización no disponible" });
      const result = await updateOrganizationProfileForUser(ctx.user.id, input);
      if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "No hay una organización activa" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "organization.profile.updated", resourceType: "organization", resourceId: String(scope.organization.id), metadata: input });
      return result;
    }),
  }),
  memberships: router({
    list: protectedProcedure.query(async ({ ctx }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "organization", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de consulta de membresías no disponible" });
      return listMembershipsForUser(ctx.user.id);
    }),
    updateScope: protectedProcedure.input(z.object({ membershipId: z.number().int().positive(), branchId: z.number().int().positive().nullable().optional(), warehouseId: z.number().int().positive().nullable().optional() })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "organization", "configure"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de configuración de membresías no disponible" });
      const result = await updateMembershipScopeForUser(ctx.user.id, input);
      if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "La membresía, sucursal o almacén no pertenece a la organización activa" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "membership.scope.updated", resourceType: "membership", resourceId: String(result.id), metadata: { branchId: result.branchId, warehouseId: result.warehouseId } });
      return result;
    }),
  }),
  permissions: router({
    list: protectedProcedure.query(async ({ ctx }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "organization", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de consulta de permisos no disponible" });
      return listRolePermissionsForUser(ctx.user.id);
    }),
    grant: protectedProcedure.input(z.object({ role: z.enum(["owner", "manager", "support", "finance", "supervisor", "warehouse", "dispatcher", "driver", "customer"]), resource: z.string().trim().min(2).max(80), action: z.enum(["view", "create", "edit", "approve", "assign", "collect", "refund", "export", "configure"]) })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "organization", "configure"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de configuración de permisos no disponible" });
      const result = await grantRolePermissionForUser(ctx.user.id, input);
      if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "No se pudo conceder el permiso" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "role.permission.granted", resourceType: "role_permission", resourceId: String(result.id), metadata: input });
      return result;
    }),
    revoke: protectedProcedure.input(z.object({ permissionId: z.number().int().positive() })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "organization", "configure"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de configuración de permisos no disponible" });
      const result = await revokeRolePermissionForUser(ctx.user.id, input.permissionId);
      if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Permiso no encontrado en la organización activa" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "role.permission.revoked", resourceType: "role_permission", resourceId: String(result.id), metadata: { role: result.role, resource: result.resource, action: result.action } });
      return result;
    }),
  }),
  system: systemRouter,
  customer: router({
    profile: protectedProcedure.query(async ({ ctx }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope) throw new TRPCError({ code: "FORBIDDEN", message: "No hay una organización activa" });
      const result = await getCustomerProfileForUser(ctx.user.id);
      return { ...result, user: { id: ctx.user.id, name: ctx.user.name, email: ctx.user.email } };
    }),
    updateProfile: protectedProcedure.input(z.object({ customerType: z.enum(["individual", "business"]), legalName: z.string().trim().max(220).nullable().optional(), phone: z.string().trim().max(40).nullable().optional(), taxId: z.string().trim().max(80).nullable().optional(), preferredLanguage: z.string().trim().min(2).max(8).default("es") })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope) throw new TRPCError({ code: "FORBIDDEN", message: "No hay una organización activa" });
      const result = await upsertCustomerProfileForUser(ctx.user.id, input);
      if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "No se pudo guardar el perfil de cliente" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "customer.profile.updated", resourceType: "customer_profile", resourceId: String(result.id), metadata: { customerType: result.customerType } });
      return result;
    }),
    addresses: router({
      list: protectedProcedure.query(({ ctx }) => listCustomerAddressesForUser(ctx.user.id)),
      create: protectedProcedure.input(z.object({ label: z.string().trim().min(2).max(80), recipientName: z.string().trim().min(2).max(180), phone: z.string().trim().max(40).nullable().optional(), addressLine1: z.string().trim().min(5).max(240), addressLine2: z.string().trim().max(240).nullable().optional(), city: z.string().trim().min(2).max(120), province: z.string().trim().min(2).max(120), country: z.string().trim().min(2).max(80).default("DO"), postalCode: z.string().trim().max(24).nullable().optional(), deliveryInstructions: z.string().trim().max(1000).nullable().optional(), latitude: z.string().regex(/^-?\d+(\.\d+)?$/).nullable().optional(), longitude: z.string().regex(/^-?\d+(\.\d+)?$/).nullable().optional(), isDefault: z.boolean().optional() })).mutation(async ({ ctx, input }) => {
        const scope = await getOrganizationForUser(ctx.user.id); if (!scope) throw new TRPCError({ code: "FORBIDDEN", message: "No hay una organización activa" });
        const result = await createCustomerAddressForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "No se pudo guardar la dirección" });
        await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "customer.address.created", resourceType: "customer_address", resourceId: String(result.id), metadata: { label: result.label, isDefault: result.isDefault } }); return result;
      }),
      update: protectedProcedure.input(z.object({ addressId: z.number().int().positive(), label: z.string().trim().min(2).max(80).optional(), recipientName: z.string().trim().min(2).max(180).optional(), phone: z.string().trim().max(40).nullable().optional(), addressLine1: z.string().trim().min(5).max(240).optional(), addressLine2: z.string().trim().max(240).nullable().optional(), city: z.string().trim().min(2).max(120).optional(), province: z.string().trim().min(2).max(120).optional(), country: z.string().trim().min(2).max(80).optional(), postalCode: z.string().trim().max(24).nullable().optional(), deliveryInstructions: z.string().trim().max(1000).nullable().optional(), latitude: z.string().regex(/^-?\d+(\.\d+)?$/).nullable().optional(), longitude: z.string().regex(/^-?\d+(\.\d+)?$/).nullable().optional(), isDefault: z.boolean().optional(), isActive: z.boolean().optional() })).mutation(async ({ ctx, input }) => {
        const scope = await getOrganizationForUser(ctx.user.id); if (!scope) throw new TRPCError({ code: "FORBIDDEN", message: "No hay una organización activa" }); const { addressId, ...changes } = input; const result = await updateCustomerAddressForUser(ctx.user.id, addressId, changes); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Dirección no encontrada en tu organización" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "customer.address.updated", resourceType: "customer_address", resourceId: String(result.id), metadata: changes }); return result;
      }),
    }),
    contacts: router({
      list: protectedProcedure.query(({ ctx }) => listCustomerContactsForUser(ctx.user.id)),
      create: protectedProcedure.input(z.object({ name: z.string().trim().min(2).max(180), relationship: z.string().trim().max(80).nullable().optional(), phone: z.string().trim().max(40).nullable().optional(), email: z.string().email().max(320).nullable().optional(), notes: z.string().trim().max(1000).nullable().optional() })).mutation(async ({ ctx, input }) => {
        const scope = await getOrganizationForUser(ctx.user.id); if (!scope) throw new TRPCError({ code: "FORBIDDEN", message: "No hay una organización activa" }); const result = await createCustomerContactForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "No se pudo guardar el contacto" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "customer.contact.created", resourceType: "customer_contact", resourceId: String(result.id), metadata: { name: result.name } }); return result;
      }),
      update: protectedProcedure.input(z.object({ contactId: z.number().int().positive(), name: z.string().trim().min(2).max(180).optional(), relationship: z.string().trim().max(80).nullable().optional(), phone: z.string().trim().max(40).nullable().optional(), email: z.string().email().max(320).nullable().optional(), notes: z.string().trim().max(1000).nullable().optional(), isActive: z.boolean().optional() })).mutation(async ({ ctx, input }) => {
        const scope = await getOrganizationForUser(ctx.user.id); if (!scope) throw new TRPCError({ code: "FORBIDDEN", message: "No hay una organización activa" }); const { contactId, ...changes } = input; const result = await updateCustomerContactForUser(ctx.user.id, contactId, changes); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Contacto no encontrado en tu organización" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "customer.contact.updated", resourceType: "customer_contact", resourceId: String(result.id), metadata: changes }); return result;
      }),
    }),
    tickets: router({
      list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope) throw new TRPCError({ code: "FORBIDDEN", message: "No hay una organización activa" }); const ownOnly = scope.membership.role === "customer"; if (!ownOnly && !(await canUser(ctx.user.id, scope.organization.id, "support_tickets", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de consulta de tickets no disponible" }); return listSupportTicketsForUser(ctx.user.id, ownOnly); }),
      create: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive().nullable().optional(), subject: z.string().trim().min(5).max(180), description: z.string().trim().min(10).max(4000), category: z.enum(["shipment", "billing", "pickup", "delivery", "account", "other"]).default("other"), priority: z.enum(["low", "normal", "high", "urgent"]).default("normal") })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || (scope.membership.role !== "customer" && !(await canUser(ctx.user.id, scope.organization.id, "support_tickets", "create")))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso para crear tickets no disponible" }); const result = await createSupportTicketForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "El envío no pertenece a tu organización o no se pudo crear el ticket" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "support.ticket.created", resourceType: "support_ticket", resourceId: String(result.id), metadata: { category: result.category, priority: result.priority, shipmentId: result.shipmentId } }); return result; }),
      manage: protectedProcedure.input(z.object({ ticketId: z.number().int().positive(), status: z.enum(["open", "in_progress", "waiting_customer", "resolved", "closed"]).optional(), priority: z.enum(["low", "normal", "high", "urgent"]).optional(), resolution: z.string().trim().max(4000).nullable().optional(), assignedTo: z.number().int().positive().nullable().optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || scope.membership.role === "customer" || !(await canUser(ctx.user.id, scope.organization.id, "support_tickets", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de gestión de tickets no disponible" }); const { ticketId, ...changes } = input; const result = await updateSupportTicketForUser(ctx.user.id, ticketId, changes); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Ticket no encontrado en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "support.ticket.updated", resourceType: "support_ticket", resourceId: String(result.id), metadata: changes }); return result; }),
    }),
  }),
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      return { success: true } as const;
    }),
  }),
  logistics: router({
    scope: protectedProcedure.query(async ({ ctx }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope) return null;
      return { organization: scope.organization, role: scope.membership.role, branchId: scope.membership.branchId };
    }),
    shipments: router({
      list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de envíos no disponible" }); return listShipmentsForUser(ctx.user.id); }),
      export: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", "export"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de exportación de envíos no disponible" }); const rows = await listShipmentsForUser(ctx.user.id); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "shipment.exported", resourceType: "shipment", metadata: { count: rows.length } }); return rows; }),
      create: protectedProcedure.input(z.object({ branchId: z.number().int().positive().optional(), serviceType: z.enum(["local", "national", "international", "assisted_purchase", "heavy_cargo", "moving"]), senderName: z.string().min(2).max(180), recipientName: z.string().min(2).max(180), originAddress: z.string().min(5).max(1000), destinationAddress: z.string().min(5).max(1000), originCountry: z.string().min(2).max(80).default("DO"), destinationCountry: z.string().min(2).max(80).default("DO"), estimatedAmount: z.string().regex(/^\d+(\.\d{1,2})?$/).optional(), deliveryPin: z.string().regex(/^\d{4,8}$/).optional() })).mutation(async ({ ctx, input }) => {
        const scope = await getOrganizationForUser(ctx.user.id);
        if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de creación de envíos no disponible" });
        const result = await createShipmentForUser(ctx.user.id, input);
        if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "La sucursal no pertenece a la organización activa" });
        await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "shipment.created", resourceType: "shipment", resourceId: String(result.id), metadata: { trackingCode: result.trackingCode, serviceType: result.serviceType } });
        return result;
      }),
      update: protectedProcedure.input(z.object({ id: z.number().int().positive(), branchId: z.number().int().positive().optional(), serviceType: z.enum(["local", "national", "international", "assisted_purchase", "heavy_cargo", "moving"]).optional(), senderName: z.string().min(2).max(180).optional(), recipientName: z.string().min(2).max(180).optional(), originAddress: z.string().min(5).max(1000).optional(), destinationAddress: z.string().min(5).max(1000).optional(), originCountry: z.string().min(2).max(80).optional(), destinationCountry: z.string().min(2).max(80).optional(), estimatedAmount: z.string().regex(/^\d+(\.\d{1,2})?$/).optional() })).mutation(async ({ ctx, input }) => {
        const scope = await getOrganizationForUser(ctx.user.id);
        if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de edición de envíos no disponible" });
        const { id, ...changes } = input;
        const result = await updateShipmentForUser(ctx.user.id, id, changes);
        if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Envío no encontrado o ya no está editable" });
        await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "shipment.updated", resourceType: "shipment", resourceId: String(id), metadata: changes });
        return result;
      }),
      cancel: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => {
        const scope = await getOrganizationForUser(ctx.user.id);
        if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de cancelación de envíos no disponible" });
        const result = await cancelShipmentForUser(ctx.user.id, input.id);
        if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "El envío no existe, ya fue procesado o no puede cancelarse en su estado actual" });
        await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "shipment.cancelled", resourceType: "shipment", resourceId: String(result.id), metadata: { trackingCode: result.trackingCode, nextState: result.commercialStatus } });
        return result;
      }),
    }),
    timeline: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive() })).query(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "tracking", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de timeline no disponible" }); return listEventsForUser(ctx.user.id, input.shipmentId); }),
    appendEvent: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive(), eventType: z.string().min(2), nextStatus: z.string().optional(), note: z.string().optional(), reason: z.string().max(500).optional(), branchId: z.number().int().positive().optional(), evidenceUrl: z.string().url().optional(), latitude: z.number().optional(), longitude: z.number().optional(), idempotencyKey: z.string().min(8), origin: z.string().min(2).default("operator") })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "tracking", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de modificación de timeline no disponible" });
      const persisted = await appendShipmentEvent({ ...input, latitude: input.latitude === undefined ? undefined : String(input.latitude), longitude: input.longitude === undefined ? undefined : String(input.longitude), organizationId: scope.organization.id, actorUserId: ctx.user.id });
      if (persisted === false) throw new TRPCError({ code: "FORBIDDEN", message: "Envío no perteneciente a la organización activa" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "shipment.event.appended", resourceType: "shipment", resourceId: String(input.shipmentId), metadata: input });
      return { success: true } as const;
    }),
    confirmDelivery: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive(), recipientName: z.string().min(2).max(180), deliveryPin: z.string().regex(/^\d{4,8}$/).optional(), note: z.string().max(1000).optional(), evidenceUrl: z.string().url().optional(), latitude: z.number().gte(-90).lte(90).optional(), longitude: z.number().gte(-180).lte(180).optional(), idempotencyKey: z.string().min(8).max(120) })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "tracking", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de confirmación de entrega no disponible" });
      try {
        const result = await confirmShipmentDeliveryForUser(ctx.user.id, { ...input, latitude: input.latitude === undefined ? undefined : String(input.latitude), longitude: input.longitude === undefined ? undefined : String(input.longitude) });
        if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Envío no encontrado en la organización activa" });
        await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "shipment.delivery.confirmed", resourceType: "shipment", resourceId: String(input.shipmentId), metadata: { recipientName: input.recipientName, evidenceProvided: Boolean(input.evidenceUrl), idempotencyKey: input.idempotencyKey } });
        return result;
      } catch (error) {
        if (error instanceof TRPCError) throw error;
        throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Entrega no confirmada" });
      }
    }),
    overview: protectedProcedure.query(async ({ ctx }) => {
      const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de KPI de envíos no disponible" });
      const shipments = await listShipmentsForUser(ctx.user.id);
      const packages = await listPackagesForUser(ctx.user.id);
      return {
        active: shipments.filter((item) => !["delivered", "returned", "cancelled"].includes(item.physicalStatus)).length,
        inDelivery: shipments.filter((item) => item.physicalStatus === "out_for_delivery").length,
        incidents: shipments.filter((item) => item.physicalStatus === "incident").length,
        total: shipments.length,
        packages: packages.length,
      };
    }),
    audit: protectedProcedure.input(z.object({ category: z.enum(["operational", "financial", "security", "llm"]), action: z.string().min(2), resourceType: z.string().optional(), resourceId: z.string().optional(), metadata: z.unknown().optional() })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "audit", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de registro de auditoría no disponible" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, ...input });
      return { success: true } as const;
    }),
  }),
  agent: router({
    suggest: protectedProcedure.input(z.object({ context: z.string().min(5).max(6000), requestedAction: z.string().optional() })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope) throw new TRPCError({ code: "FORBIDDEN", message: "No hay una organización activa para el agente" });
      const response = await invokeLLM({
        messages: [
          { role: "system", content: "Eres el agente operativo de GoPaq. Analiza el contexto logístico en español. No confirmes entregas, pagos ni cambios de estado: devuelve siempre una propuesta que requiera aprobación humana." },
          { role: "user", content: `Contexto: ${input.context}${input.requestedAction ? `\nAcción solicitada: ${input.requestedAction}` : ""}` },
        ],
        response_format: { type: "json_schema", json_schema: { name: "gopaq_agent_suggestion", strict: true, schema: { type: "object", properties: { summary: { type: "string" }, priority: { type: "string", enum: ["low", "medium", "high"] }, proposedAction: { type: "string" }, actionType: { type: "string", enum: [...AGENT_ACTION_TYPES] }, requiresApproval: { type: "boolean" }, rationale: { type: "string" } }, required: ["summary", "priority", "proposedAction", "actionType", "requiresApproval", "rationale"], additionalProperties: false } } },
      });
      const content = response.choices?.[0]?.message?.content;
      const rawSuggestion = typeof content === "string" ? JSON.parse(content) : { summary: "No hay sugerencias disponibles", priority: "low", proposedAction: "Ninguna acción", actionType: "detect_anomaly" as const, requiresApproval: true, rationale: "Respuesta del agente no disponible" };
      let suggestion: ReturnType<typeof enforceAgentApproval>;
      try {
        suggestion = enforceAgentApproval(rawSuggestion, input.requestedAction);
      } catch (error) {
        await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "agent.suggestion.blocked", resourceType: "agent", metadata: { reason: "approval_required" } });
        throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Proposta agente bloccata" });
      }
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "llm", action: "agent.suggestion.created", resourceType: "agent", metadata: { ...suggestion, sensitive: suggestion.sensitive, approved: false } });
      return suggestion;
    }),
  }),
  packages: router({
    list: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive().optional() }).optional()).query(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "packages", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de paquetes no disponible" }); return listPackagesForUser(ctx.user.id, input?.shipmentId); }),
    create: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive(), packageCode: z.string().min(3).max(48).regex(/^[A-Za-z0-9_-]+$/).optional(), description: z.string().max(1000).optional(), restrictions: z.string().max(1000).optional(), weight: z.number().positive().optional(), weightUnit: z.enum(["kg", "g", "lb", "oz"]).default("kg"), length: z.number().positive().optional(), width: z.number().positive().optional(), height: z.number().positive().optional(), dimensionUnit: z.enum(["cm", "in"]).default("cm"), declaredValue: z.string().regex(/^\d+(\.\d{1,2})?$/).optional(), locationCode: z.string().max(80).optional(), barcodeValue: z.string().max(120).optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "packages", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de creación de paquetes no disponible" }); const result = await createPackageForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "El envío no pertenece a la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "package.created", resourceType: "package", resourceId: String(result.id), metadata: { shipmentId: input.shipmentId, weightUnit: input.weightUnit, dimensionUnit: input.dimensionUnit } }); return result; }),
    update: protectedProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["expected", "received", "inspected", "stored", "dispatched", "delivered", "incident", "returned"]).optional(), description: z.string().max(1000).optional(), restrictions: z.string().max(1000).optional(), weight: z.number().positive().optional(), weightUnit: z.enum(["kg", "g", "lb", "oz"]).default("kg"), length: z.number().positive().optional(), width: z.number().positive().optional(), height: z.number().positive().optional(), dimensionUnit: z.enum(["cm", "in"]).default("cm"), declaredValue: z.string().regex(/^\d+(\.\d{1,2})?$/).optional(), locationCode: z.string().max(80).optional(), barcodeValue: z.string().max(120).optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "packages", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de edición de paquetes no disponible" }); const { id, ...changes } = input; try { const result = await updatePackageForUser(ctx.user.id, id, changes); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Paquete no encontrado en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "package.updated", resourceType: "package", resourceId: String(id), metadata: { status: input.status, locationCode: input.locationCode, weightUnit: input.weightUnit, dimensionUnit: input.dimensionUnit } }); return result; } catch (error) { if (error instanceof TRPCError) throw error; throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Transición de paquete no válida" }); } }),
    split: protectedProcedure.input(z.object({ packageId: z.number().int().positive(), children: z.array(z.object({ description: z.string().max(1000).optional(), weight: z.number().positive(), weightUnit: z.enum(["kg", "g", "lb", "oz"]).default("kg"), length: z.number().positive().optional(), width: z.number().positive().optional(), height: z.number().positive().optional(), dimensionUnit: z.enum(["cm", "in"]).default("cm"), declaredValue: z.string().regex(/^\d+(\.\d{1,2})?$/).optional(), barcodeValue: z.string().max(120).optional(), locationCode: z.string().max(80).optional() })).min(2).max(20) })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "packages", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de separación de paquetes no disponible" }); try { const result = await splitPackageForUser(ctx.user.id, input.packageId, input.children); if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "El paquete no puede separarse o está fuera de la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "package.split", resourceType: "package", resourceId: String(input.packageId), metadata: { childCount: result.children.length } }); return result; } catch (error) { if (error instanceof TRPCError) throw error; throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Separación de paquete no válida" }); } }),
    repack: protectedProcedure.input(z.object({ packageId: z.number().int().positive(), warehouseId: z.number().int().positive().optional(), locationCode: z.string().max(80).optional(), weight: z.number().positive().optional(), weightUnit: z.enum(["kg", "g", "lb", "oz"]).default("kg"), length: z.number().positive().optional(), width: z.number().positive().optional(), height: z.number().positive().optional(), dimensionUnit: z.enum(["cm", "in"]).default("cm"), note: z.string().max(1000).optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "packages", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de reempaque de paquetes no disponible" }); const { packageId, ...changes } = input; try { const result = await repackPackageForUser(ctx.user.id, packageId, changes); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Paquete o almacén no encontrado en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "package.repacked", resourceType: "package", resourceId: String(packageId), metadata: { warehouseId: input.warehouseId, locationCode: input.locationCode, weightUnit: input.weightUnit, dimensionUnit: input.dimensionUnit } }); return result; } catch (error) { if (error instanceof TRPCError) throw error; throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Reempaque de paquete no válido" }); } }),
  }),
  inventory: router({
    list: protectedProcedure.input(z.object({ packageId: z.number().int().positive().optional() }).optional()).query(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "packages", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de inventario no disponible" }); return listInventoryMovementsForUser(ctx.user.id, input?.packageId); }),
    move: protectedProcedure.input(z.object({ packageId: z.number().int().positive(), warehouseId: z.number().int().positive().optional(), movementType: z.enum(["received", "inspected", "putaway", "transfer_out", "transfer_in", "dispatch", "adjustment"]), fromLocation: z.string().max(80).optional(), toLocation: z.string().max(80).optional(), note: z.string().max(1000).optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "packages", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de movimientos de inventario no disponible" }); try { const result = await recordInventoryMovementForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Paquete o almacén no encontrado en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "inventory.movement.recorded", resourceType: "package", resourceId: String(input.packageId), metadata: input }); return result; } catch (error) { if (error instanceof TRPCError) throw error; throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Movimiento de inventario no válido" }); } }),
  }),
  consolidations: router({
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "manifests", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de consolidaciones no disponible" }); return listConsolidationsForUser(ctx.user.id); }),
    create: protectedProcedure.input(z.object({ fromBranchId: z.number().int().positive().optional(), toBranchId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "manifests", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de creación de consolidaciones no disponible" }); const result = await createConsolidationForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "Las sucursales no pertenecen a la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "consolidation.created", resourceType: "consolidation", resourceId: String(result.id), metadata: input }); return result; }),
    addPackage: protectedProcedure.input(z.object({ consolidationId: z.number().int().positive(), packageId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "manifests", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de carga de consolidaciones no disponible" }); const result = await addPackageToConsolidationForUser(ctx.user.id, input.consolidationId, input.packageId); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Consolidación o paquete no encontrado, cerrado o fuera de la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "consolidation.package_added", resourceType: "consolidation", resourceId: String(input.consolidationId), metadata: { packageId: input.packageId } }); return result; }),
    advance: protectedProcedure.input(z.object({ consolidationId: z.number().int().positive(), nextStatus: z.enum(["sealed", "in_transit", "received", "reconciled"]) })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "manifests", ["sealed", "reconciled"].includes(input.nextStatus) ? "approve" : "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: ["sealed", "reconciled"].includes(input.nextStatus) ? "Permiso de aprobación de consolidaciones no disponible" : "Permiso de avance de consolidaciones no disponible" }); try { const result = await advanceConsolidationForUser(ctx.user.id, input.consolidationId, input.nextStatus); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Consolidación no encontrada" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "consolidation.advanced", resourceType: "consolidation", resourceId: String(input.consolidationId), metadata: { nextStatus: input.nextStatus } }); return result; } catch (error) { if (error instanceof TRPCError) throw error; throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Transición de consolidación no válida" }); } }),
  }),
  incidents: router({
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de incidencias no disponible" }); return listIncidentsForUser(ctx.user.id); }),
    create: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive(), packageId: z.number().int().positive().optional(), type: z.enum(["damage", "address", "recipient_unavailable", "customs", "other", "return_requested"]), severity: z.enum(["low", "medium", "high", "critical"]).default("medium"), description: z.string().min(5).max(2000) })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de registro de incidencias no disponible" }); const result = await createIncidentForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Envío o paquete no encontrado en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "shipment.incident.created", resourceType: "shipment_incident", resourceId: String(result.id), metadata: { shipmentId: input.shipmentId, packageId: input.packageId, type: input.type, severity: input.severity } }); return result; }),
    resolve: protectedProcedure.input(z.object({ incidentId: z.number().int().positive(), status: z.enum(["investigating", "resolved", "returned"]), resolution: z.string().max(2000).optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", input.status === "returned" ? "approve" : "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: input.status === "returned" ? "Permiso de aprobación de devolución no disponible" : "Permiso de resolución de incidencias no disponible" }); try { const result = await resolveIncidentForUser(ctx.user.id, input.incidentId, input); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Incidencia no encontrada en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "shipment.incident.resolved", resourceType: "shipment_incident", resourceId: String(input.incidentId), metadata: { status: input.status } }); return result; } catch (error) { if (error instanceof TRPCError) throw error; throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Transición de incidencia no válida" }); } }),
  }),
  deliveryAttempts: router({
    list: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive().optional() }).optional()).query(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de intentos de entrega no disponible" }); return listDeliveryAttemptsForUser(ctx.user.id, input?.shipmentId); }),
    create: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive(), routeStopId: z.number().int().positive().optional(), status: z.enum(["failed", "rescheduled", "completed"]), reason: z.string().min(3).max(160), note: z.string().max(1000).optional(), latitude: z.string().regex(/^-?\\d+(\\.\\d+)?$/).optional(), longitude: z.string().regex(/^-?\\d+(\\.\\d+)?$/).optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de registro de intentos no disponible" }); if (scope.membership?.role === "driver" && (!input.routeStopId || !(await isActiveRouteStopAssignedToUser(ctx.user.id, input.routeStopId)))) throw new TRPCError({ code: "FORBIDDEN", message: "El intento debe corresponder a una parada de tu ruta activa" }); const result = await recordDeliveryAttemptForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Envío o parada no encontrada en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "shipment.delivery_attempt.recorded", resourceType: "delivery_attempt", resourceId: String(result.id), metadata: { shipmentId: input.shipmentId, routeStopId: input.routeStopId, status: input.status, reason: input.reason } }); return result; }),
  }),
  payments: router({
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "payments", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de cobros no disponible" }); return listPaymentsForUser(ctx.user.id); }),
    export: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "payments", "export"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de exportación de cobros no disponible" }); const rows = await listPaymentsForUser(ctx.user.id); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "payment.exported", resourceType: "payment", metadata: { count: rows.length } }); return rows; }),
    collect: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive(), amount: z.string().regex(/^\d+(\.\d{1,2})?$/), method: z.enum(["cash", "card", "transfer", "other"]), reference: z.string().max(160).optional(), cashSessionId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "payments", "collect"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de registro de cobros no disponible" }); const result = await collectPaymentForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Envío o caja abierta no encontrada en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "financial", action: "payment.collected", resourceType: "payment", resourceId: String(result.payment.id), metadata: { shipmentId: input.shipmentId, amount: input.amount, method: input.method, receiptNumber: result.receipt.receiptNumber } }); return result; }),
    refund: protectedProcedure.input(z.object({ paymentId: z.number().int().positive(), reason: z.string().trim().min(5).max(500), cashSessionId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "payments", "refund"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de reembolso no disponible" }); const result = await refundPaymentForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "El cobro no existe, ya fue reembolsado o la caja no está abierta" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "financial", action: "payment.refunded", resourceType: "payment", resourceId: String(result.id), metadata: { reason: input.reason, amount: result.amount, method: result.method } }); return result; }),
  }),
  cash: router({
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "cash", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de caja no disponible" }); return listCashSessionsForUser(ctx.user.id); }),
    open: protectedProcedure.input(z.object({ branchId: z.number().int().positive(), openingAmount: z.string().regex(/^\d+(\.\d{1,2})?$/) })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "cash", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de apertura de caja no disponible" }); const result = await openCashSessionForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "La sucursal no es válida o ya tiene una caja abierta" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "financial", action: "cash.opened", resourceType: "cash_session", resourceId: String(result.id), metadata: { branchId: input.branchId, openingAmount: input.openingAmount } }); return result; }),
    close: protectedProcedure.input(z.object({ sessionId: z.number().int().positive(), closingAmount: z.string().regex(/^\d+(\.\d{1,2})?$/) })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "cash", "approve"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de aprobación de cierre de caja no disponible" }); const result = await closeCashSessionForUser(ctx.user.id, input.sessionId, input.closingAmount); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Caja abierta no encontrada en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "financial", action: "cash.closed", resourceType: "cash_session", resourceId: String(result.id), metadata: { closingAmount: input.closingAmount } }); return result; }),
  }),
  invoices: router({
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "invoices", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de facturas no disponible" }); return listInvoicesForUser(ctx.user.id); }),
    export: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "invoices", "export"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de exportación de facturas no disponible" }); const rows = await listInvoicesForUser(ctx.user.id); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "invoice.exported", resourceType: "invoice", metadata: { count: rows.length } }); return rows; }),
    issue: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive(), subtotal: z.string().regex(/^\d+(\.\d{1,2})?$/), tax: z.string().regex(/^\d+(\.\d{1,2})?$/).default("0") })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "invoices", "approve"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de aprobación de emisión de facturas no disponible" }); const result = await issueInvoiceForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Envío no encontrado en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "financial", action: "invoice.issued", resourceType: "invoice", resourceId: String(result.id), metadata: { shipmentId: input.shipmentId, total: result.total, currency: result.currency } }); return result; }),
  }),
  services: router({
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de servicios especiales no disponible" }); return listShipmentServicesForUser(ctx.user.id); }),
    create: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive(), serviceType: z.enum(["assisted_purchase", "heavy_cargo", "moving"]), quoteReference: z.string().max(160).optional(), handlingNotes: z.string().max(2000).optional(), scheduledAt: z.coerce.date().optional(), crewSize: z.number().int().min(1).max(20).optional(), vehicleType: z.string().trim().min(2).max(100).optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de solicitud de servicio especial no disponible" }); const result = await createShipmentServiceForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Envío no encontrado en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "shipment.service.created", resourceType: "shipment_service", resourceId: String(result.id), metadata: { shipmentId: input.shipmentId, serviceType: input.serviceType } }); return result; }),
    update: protectedProcedure.input(z.object({ serviceId: z.number().int().positive(), status: z.enum(["quoted", "awaiting_approval", "approved", "purchasing", "purchased", "fulfillment", "scheduled", "in_progress", "completed", "cancelled", "rejected"]), quoteReference: z.string().max(160).optional(), handlingNotes: z.string().max(2000).optional(), scheduledAt: z.coerce.date().optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "shipments", ["approved", "rejected"].includes(input.status) ? "approve" : "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: ["approved", "rejected"].includes(input.status) ? "Permiso de aprobación de servicio especial no disponible" : "Permiso de actualización de servicio especial no disponible" }); const { serviceId, ...changes } = input; try { const result = await updateShipmentServiceForUser(ctx.user.id, serviceId, changes); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Servicio especial no encontrado en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "shipment.service.updated", resourceType: "shipment_service", resourceId: String(serviceId), metadata: { status: input.status } }); return result; } catch (error) { if (error instanceof TRPCError) throw error; throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Transición de servicio especial no válida" }); } }),
  }),
  audit: router({
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "audit", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de auditoría no disponible" }); return listAuditLogsForUser(ctx.user.id); }),
  }),
  apiLogs: router({
    list: protectedProcedure.input(z.object({ statusCode: z.number().int().min(100).max(599).optional(), route: z.string().max(160).optional() }).optional()).query(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "audit", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de auditoría API no disponible" }); return listApiRequestLogsForUser(ctx.user.id, input); }),
  }),
  documents: router({
    upload: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive(), documentType: z.enum(["label", "invoice", "customs", "pod", "incident", "receipt"]), fileName: z.string().min(1).max(180).regex(/^[a-zA-Z0-9._-]+$/), mimeType: z.string().min(3).max(120), dataBase64: z.string().min(1) })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "documents", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de documentos no disponible" });
      const result = await uploadShipmentDocumentForUser(ctx.user.id, input);
      if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "El envío no pertenece a la organización activa" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "shipment.document.uploaded", resourceType: "shipment_document", resourceId: String(input.shipmentId), metadata: { documentType: input.documentType, mimeType: input.mimeType } });
      return result;
    }),
    list: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive().optional() }).optional()).query(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "documents", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de documentos no disponible" }); return listShipmentDocumentsForUser(ctx.user.id, input?.shipmentId); }),
  }),
  apiKeys: router({
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "api_keys", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de claves API no disponible" }); return listApiKeysForUser(ctx.user.id); }),
    issue: protectedProcedure.input(z.object({ name: z.string().min(2).max(160), scopes: z.array(z.enum(["quotes:read", "shipments:read", "shipments:write", "tracking:read", "pickups:write", "webhooks:read"])).min(1).max(10) })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "api_keys", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de API no disponible" });
      const key = await createApiKeyForUser(ctx.user.id, input.name, input.scopes);
      if (!key) throw new TRPCError({ code: "FORBIDDEN", message: "No hay una organización activa" });
      return key;
    }),
    revoke: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "api_keys", "configure"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de API no disponible" });
      const revoked = await revokeApiKeyForUser(ctx.user.id, input.id);
      if (!revoked) throw new TRPCError({ code: "NOT_FOUND", message: "Clave API no encontrada" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "api_key.revoked", resourceType: "api_key", resourceId: String(input.id), metadata: { revoked: true } });
      return { success: true } as const;
    }),
  }),
  gps: router({
    points: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive().optional(), routeId: z.number().int().positive().optional() })).query(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "tracking", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de tracking no disponible" }); const result = await listTrackingPointsForUser(ctx.user.id, input.shipmentId, input.routeId); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "security", action: "tracking.points.viewed", resourceType: "tracking_points", resourceId: trackingResourceId(input), metadata: buildTrackingAuditMetadata(input, result.length) }); return result; }),
    record: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive().optional(), routeId: z.number().int().positive().optional(), latitude: z.number().gte(-90).lte(90), longitude: z.number().gte(-180).lte(180), accuracyMeters: z.number().nonnegative().optional(), capturedAt: z.date(), source: z.enum(["driver", "branch", "system"]).default("driver") })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "tracking", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de registro de tracking no disponible" });
      const result = await recordTrackingPoint(ctx.user.id, { ...input, latitude: String(input.latitude), longitude: String(input.longitude), accuracyMeters: input.accuracyMeters === undefined ? undefined : String(input.accuracyMeters) });
      if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "Punto GPS sin envío o ruta válida de la organización" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "tracking.point.recorded", resourceType: "tracking_point", resourceId: String(input.shipmentId ?? input.routeId ?? "unassigned"), metadata: { shipmentId: input.shipmentId, routeId: input.routeId, source: input.source } });
      return result;
    }),
  }),
  quote: router({
    preview: publicProcedure.input(z.object({ organizationSlug: z.string().trim().min(2).max(100), serviceType: z.enum(["local", "national", "international", "assisted_purchase", "heavy_cargo", "moving"]).default("national"), zoneCode: z.string().trim().min(1).max(40).optional(), actualWeightKg: z.number().positive(), lengthCm: z.number().positive(), widthCm: z.number().positive(), heightCm: z.number().positive(), distanceKm: z.number().nonnegative() })).query(async ({ input }) => { const organization = await getOrganizationBySlug(input.organizationSlug); if (!organization) throw new TRPCError({ code: "NOT_FOUND", message: "Organización pública no encontrada o inactiva" }); const tariff = await getActiveTariffForOrganization(organization.id, input.serviceType, input.zoneCode); if (!tariff) throw new TRPCError({ code: "CONFLICT", message: "No existe una tarifa vigente para este servicio y zona" }); const { organizationSlug, serviceType, zoneCode, ...measurements } = input; const tariffInput = { ...measurements, minAmount: Number(tariff.minAmount), perKg: Number(tariff.perKg), perKm: Number(tariff.perKm), fixedSurcharge: Number(tariff.fixedSurcharge ?? 0), fuelSurchargePct: Number(tariff.fuelSurchargePct ?? 0), discountPct: Number(tariff.discountPct ?? 0), taxPct: Number(tariff.taxPct ?? 0), volumetricDivisor: Number(tariff.volumetricDivisor ?? 5000) }; return { ...calculateQuote(tariffInput), currency: tariff.currency, serviceType, zoneCode: zoneCode ?? null, organizationSlug, tariffVersion: tariff.version }; }),
  }),
  routes: router({
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de rutas no disponible" }); return scope.membership?.role === "driver" ? listAssignedRoutesForUser(ctx.user.id) : listRoutesForUser(ctx.user.id); }),
    create: protectedProcedure.input(z.object({ branchId: z.number().int().positive().optional(), vehicleLabel: z.string().max(100).optional() })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de creación de rutas no disponible" });
      const result = await createRouteForUser(ctx.user.id, input);
      if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "La sucursal no pertenece a la organización activa" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "route.created", resourceType: "route", resourceId: String(result.id), metadata: { code: result.code, branchId: result.branchId } });
      return result;
    }),
    assign: protectedProcedure.input(z.object({ routeId: z.number().int().positive(), driverUserId: z.number().int().positive() })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", "assign"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de asignación de rutas no disponible" });
      const result = await assignRouteForUser(ctx.user.id, input.routeId, input.driverUserId);
      if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Ruta o conductor no encontrado en la organización activa" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "route.assigned", resourceType: "route", resourceId: String(input.routeId), metadata: { driverUserId: input.driverUserId } });
      return result;
    }),
    myAssigned: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de rutas asignadas no disponible" }); return listAssignedRoutesForUser(ctx.user.id); }),
    myStops: protectedProcedure.input(z.object({ routeId: z.number().int().positive() })).query(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de paradas asignadas no disponible" }); if (scope.membership?.role === "driver" && !(await isRouteAssignedToUser(ctx.user.id, input.routeId))) throw new TRPCError({ code: "FORBIDDEN", message: "La ruta no está asignada al conductor" }); return scope.membership?.role === "driver" ? listAssignedRouteStopsForUser(ctx.user.id, input.routeId) : listRouteStopsForUser(ctx.user.id, input.routeId); }),
    myStatus: protectedProcedure.input(z.object({ routeId: z.number().int().positive(), nextStatus: z.enum(["active", "closed"]) })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de turno no disponible" }); if (scope.membership?.role !== "driver") throw new TRPCError({ code: "FORBIDDEN", message: "Solo el conductor asignado puede gestionar su turno" }); try { const result = await updateAssignedRouteForUser(ctx.user.id, input.routeId, input.nextStatus); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Ruta no asignada al conductor" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: input.nextStatus === "active" ? "route.shift.started" : "route.shift.closed", resourceType: "route", resourceId: String(input.routeId), metadata: { status: input.nextStatus } }); return result; } catch (error) { if (error instanceof TRPCError) throw error; throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Cambio de turno no válido" }); } }),
    stopsCreate: protectedProcedure.input(z.object({ routeId: z.number().int().positive(), shipmentId: z.number().int().positive().optional(), pickupId: z.number().int().positive().optional(), sequence: z.number().int().positive().optional(), address: z.string().min(5).max(1000), latitude: z.string().regex(/^-?\\d+(\\.\\d+)?$/).optional(), longitude: z.string().regex(/^-?\\d+(\\.\\d+)?$/).optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de edición de paradas no disponible" }); const result = await createRouteStopForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Ruta, envío o pickup no encontrado en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "route.stop.created", resourceType: "route_stop", resourceId: String(result.id), metadata: { routeId: input.routeId, shipmentId: input.shipmentId, pickupId: input.pickupId } }); return result; }),
    stopsUpdate: protectedProcedure.input(z.object({ stopId: z.number().int().positive(), status: z.enum(["pending", "arrived", "completed", "failed", "skipped"]).optional(), address: z.string().min(5).max(1000).optional(), latitude: z.string().regex(/^-?\\d+(\\.\\d+)?$/).optional(), longitude: z.string().regex(/^-?\\d+(\\.\\d+)?$/).optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de edición de paradas no disponible" }); if (scope.membership?.role === "driver" && !(await isRouteStopAssignedToUser(ctx.user.id, input.stopId))) throw new TRPCError({ code: "FORBIDDEN", message: "La parada no está asignada al conductor" }); const { stopId, ...changes } = input; try { const result = await updateRouteStopForUser(ctx.user.id, stopId, changes); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Parada no encontrada en la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "route.stop.updated", resourceType: "route_stop", resourceId: String(stopId), metadata: changes }); return result; } catch (error) { if (error instanceof TRPCError) throw error; throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Transición de parada no válida" }); } }),
    scan: protectedProcedure.input(z.object({ barcodeValue: z.string().min(3).max(120), routeId: z.number().int().positive().optional(), stopId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de escaneo no disponible" }); if (scope.membership?.role === "driver" && (!input.routeId || !(await isRouteAssignedToUser(ctx.user.id, input.routeId)))) throw new TRPCError({ code: "FORBIDDEN", message: "El escaneo requiere una ruta asignada al conductor" }); const result = await scanPackageForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Código no encontrado o no vinculado a la ruta activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "package.scanned", resourceType: "package", resourceId: String(result.id), metadata: { barcodeValue: input.barcodeValue, routeId: input.routeId, stopId: input.stopId } }); return result; }),
    drivers: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", "assign"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de asignación de conductores no disponible" }); return listDriversForUser(ctx.user.id); }),
    stops: protectedProcedure.input(z.object({ routeId: z.number().int().positive() })).query(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de consulta de paradas no disponible" }); if (scope.membership?.role === "driver") return listAssignedRouteStopsForUser(ctx.user.id, input.routeId); return listRouteStopsForUser(ctx.user.id, input.routeId); }),
    expenses: protectedProcedure.input(z.object({ routeId: z.number().int().positive().optional() }).optional()).query(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de gastos de ruta no disponible" }); return listRouteExpensesForUser(ctx.user.id, input?.routeId); }),
    expenseCreate: protectedProcedure.input(z.object({ routeId: z.number().int().positive(), expenseType: z.enum(["fuel", "toll", "parking", "meal", "other"]), amount: z.string().regex(/^\d+(\.\d{1,2})?$/), description: z.string().trim().min(3).max(500), receiptUrl: z.string().url().optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de registro de gastos no disponible" }); const result = await createRouteExpenseForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "El gasto requiere una ruta asignada y activa, monto DOP válido y conductor asignado" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "financial", action: "route.expense.submitted", resourceType: "route_expense", resourceId: String(result.id), metadata: { routeId: input.routeId, expenseType: input.expenseType, amount: input.amount } }); return result; }),
    expenseReview: protectedProcedure.input(z.object({ expenseId: z.number().int().positive(), status: z.enum(["approved", "rejected", "reimbursed"]) })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); const permission = input.status === "reimbursed" ? "refund" : "approve"; if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "routes", permission))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de revisión de gastos no disponible" }); const result = await reviewRouteExpenseForUser(ctx.user.id, input.expenseId, input.status); if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "El gasto no tiene una transición válida" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "financial", action: `route.expense.${input.status}`, resourceType: "route_expense", resourceId: String(result.id), metadata: { status: input.status, amount: result.amount } }); return result; }),
  }),
  manifests: router({
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "manifests", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de manifiestos no disponible" }); return listManifestsForUser(ctx.user.id); }),
    create: protectedProcedure.input(z.object({ branchId: z.number().int().positive().optional(), direction: z.enum(["outbound", "inbound", "transfer"]) })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "manifests", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de creación de manifiestos no disponible" });
      const result = await createManifestForUser(ctx.user.id, input);
      if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "No hay una organización activa" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "manifest.created", resourceType: "manifest", resourceId: result.code, metadata: input });
      return result;
    }),
    advance: protectedProcedure.input(z.object({ manifestId: z.number().int().positive(), nextStatus: z.enum(["sealed", "in_transit", "received", "reconciled"]) })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "manifests", ["sealed", "reconciled"].includes(input.nextStatus) ? "approve" : "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: ["sealed", "reconciled"].includes(input.nextStatus) ? "Permiso de aprobación de manifiestos no disponible" : "Permiso de avance de manifiestos no disponible" }); try { const result = await advanceManifestForUser(ctx.user.id, input.manifestId, input.nextStatus); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Manifiesto no encontrado" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "manifest.advanced", resourceType: "manifest", resourceId: String(input.manifestId), metadata: { nextStatus: input.nextStatus } }); return result; } catch (error) { if (error instanceof TRPCError) throw error; throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Transizione manifest non valida" }); }
    }),
  }),
  branches: router({
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "branches", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de sucursales no disponible" }); return listBranchesForUser(ctx.user.id); }),
  }),
  tariffs: router({
    zones: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "tariffs", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de consulta tarifaria no disponible" }); return listTariffZonesForUser(ctx.user.id); }),
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "tariffs", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de consulta tarifaria no disponible" }); return listTariffsForUser(ctx.user.id); }),
    createZone: protectedProcedure.input(z.object({ code: z.string().trim().min(1).max(40).regex(/^[A-Za-z0-9_-]+$/), name: z.string().trim().min(2).max(160), originCountry: z.string().trim().min(2).max(80), destinationCountry: z.string().trim().min(2).max(80), originPostalPrefix: z.string().trim().max(20).optional(), destinationPostalPrefix: z.string().trim().max(20).optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "tariffs", "configure"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de configuración tarifaria no disponible" }); const result = await createTariffZoneForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "No se pudo crear la zona tarifaria" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "financial", action: "tariff.zone.created", resourceType: "tariff_zone", resourceId: String(result.id), metadata: input }); return result; }),
    create: protectedProcedure.input(z.object({ name: z.string().trim().min(2).max(160), serviceType: z.string().trim().min(2).max(48), zoneId: z.number().int().positive().optional(), currency: z.enum(["DOP", "USD", "EUR"]).default("DOP"), minAmount: z.string().regex(/^\d+(\.\d{1,2})?$/), perKg: z.string().regex(/^\d+(\.\d{1,2})?$/), perKm: z.string().regex(/^\d+(\.\d{1,2})?$/), fixedSurcharge: z.string().regex(/^\d+(\.\d{1,2})?$/).default("0"), fuelSurchargePct: z.string().regex(/^\d+(\.\d{1,3})?$/).default("0"), discountPct: z.string().regex(/^\d+(\.\d{1,3})?$/).default("0"), taxPct: z.string().regex(/^\d+(\.\d{1,3})?$/).default("0"), volumetricDivisor: z.string().regex(/^\d+(\.\d{1,2})?$/).default("5000"), version: z.number().int().positive(), validFrom: z.coerce.date(), validUntil: z.coerce.date().optional() })).mutation(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "tariffs", "configure"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de configuración tarifaria no disponible" }); if (input.validUntil && input.validUntil <= input.validFrom) throw new TRPCError({ code: "BAD_REQUEST", message: "La vigencia final debe ser posterior a la inicial" }); const result = await createTariffForUser(ctx.user.id, input); if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "La zona tarifaria no pertenece a la organización activa" }); await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "financial", action: "tariff.version.created", resourceType: "tariff", resourceId: String(result.id), metadata: { serviceType: input.serviceType, zoneId: input.zoneId, version: input.version, currency: input.currency } }); return result; }),
  }),
  warehouses: router({
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "warehouses", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de almacenes no disponible" }); return listWarehousesForUser(ctx.user.id); }),
    create: protectedProcedure.input(z.object({ branchId: z.number().int().positive(), name: z.string().min(2).max(160), code: z.string().min(2).max(40).regex(/^[A-Za-z0-9_-]+$/), address: z.string().max(1000).optional() })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "warehouses", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de creación de almacenes no disponible" });
      const result = await createWarehouseForUser(ctx.user.id, input);
      if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "La sucursal no pertenece a la organización activa" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "warehouse.created", resourceType: "warehouse", resourceId: String(result.id), metadata: { code: result.code, branchId: result.branchId } });
      return result;
    }),
    update: protectedProcedure.input(z.object({ id: z.number().int().positive(), branchId: z.number().int().positive().optional(), name: z.string().min(2).max(160).optional(), code: z.string().min(2).max(40).regex(/^[A-Za-z0-9_-]+$/).optional(), address: z.string().max(1000).optional(), isActive: z.boolean().optional() })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "warehouses", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de edición de almacenes no disponible" });
      const { id, ...changes } = input;
      const result = await updateWarehouseForUser(ctx.user.id, id, changes);
      if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "Almacén no encontrado" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "warehouse.updated", resourceType: "warehouse", resourceId: String(id), metadata: changes });
      return result;
    }),
  }),
  pickups: router({
    list: protectedProcedure.query(async ({ ctx }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "pickups", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de recogidas no disponible" }); return listPickupsForUser(ctx.user.id); }),
    create: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive().optional(), address: z.string().min(5).max(500), contactName: z.string().min(2).max(160), windowStart: z.date().optional(), windowEnd: z.date().optional(), notes: z.string().max(1000).optional() })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "pickups", "create"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de creación de recogidas no disponible" });
      const result = await createPickupForUser(ctx.user.id, input);
      if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "Envío no perteneciente a la organización activa o sin organización activa" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "pickup.created", resourceType: "pickup", metadata: { shipmentId: input.shipmentId, contactName: input.contactName } });
      return result;
    }),
    updateStatus: protectedProcedure.input(z.object({ pickupId: z.number().int().positive(), status: z.enum(["assigned", "en_route", "collected", "failed", "cancelled"]), evidenceUrl: z.string().url().optional(), failureReason: z.string().trim().min(3).max(500).optional(), notes: z.string().max(1000).optional() })).mutation(async ({ ctx, input }) => {
      const scope = await getOrganizationForUser(ctx.user.id);
      if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "pickups", "edit"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de actualización de recogidas no disponible" });
      const result = await updatePickupStatusForUser(ctx.user.id, input);
      if (!result) throw new TRPCError({ code: "BAD_REQUEST", message: "Transición de pickup inválida, inexistente o sin motivo de fallo" });
      await appendAuditLog({ organizationId: scope.organization.id, actorUserId: ctx.user.id, category: "operational", action: "pickup.status.changed", resourceType: "pickup", resourceId: String(input.pickupId), metadata: { previousStatus: result.previousStatus, nextStatus: input.status, hasEvidence: Boolean(input.evidenceUrl), hasFailureReason: Boolean(input.failureReason) } });
      return result.pickup;
    }),
  }),
  tracking: router({
    privateByShipment: protectedProcedure.input(z.object({ shipmentId: z.number().int().positive() })).query(async ({ ctx, input }) => { const scope = await getOrganizationForUser(ctx.user.id); if (!scope || !(await canUser(ctx.user.id, scope.organization.id, "tracking", "view"))) throw new TRPCError({ code: "FORBIDDEN", message: "Permiso de tracking privado no disponible" }); return listEventsForUser(ctx.user.id, input.shipmentId); }),
    publicByCode: publicProcedure.input(z.object({ code: z.string().min(6).max(48) })).query(async ({ input }) => {
      const result = await getPublicTrackingByCode(input.code);
      if (!result) return { trackingCode: input.code, status: "not_found" as const, message: "Inserisci un codice valido o accedi al tuo spazio cliente." };
      return { ...result, status: "found" as const };
    }),
  }),
});

export type AppRouter = typeof appRouter;
