import { useState } from "react";
import { Download, RotateCcw } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const money = new Intl.NumberFormat("es-DO", { style: "currency", currency: "DOP" });

export default function FinanceOpsPanel({ visible }: { visible: boolean }) {
  const [branchId, setBranchId] = useState("none");
  const [openingAmount, setOpeningAmount] = useState("0");
  const [sessionId, setSessionId] = useState("none");
  const [closingAmount, setClosingAmount] = useState("");
  const [shipmentId, setShipmentId] = useState("");
  const [amount, setAmount] = useState("");
  const [method, setMethod] = useState("cash");
  const [cashSessionId, setCashSessionId] = useState("none");
  const [reference, setReference] = useState("");
  const [invoiceShipmentId, setInvoiceShipmentId] = useState("");
  const [subtotal, setSubtotal] = useState("");
  const [tax, setTax] = useState("0");
  const [refundPaymentId, setRefundPaymentId] = useState("");
  const [refundReason, setRefundReason] = useState("");
  const [refundCashSessionId, setRefundCashSessionId] = useState("none");
  const [feedback, setFeedback] = useState("");
  const branches = trpc.branches.list.useQuery(undefined, { enabled: visible });
  const sessions = trpc.cash.list.useQuery(undefined, { enabled: visible });
  const payments = trpc.payments.list.useQuery(undefined, { enabled: visible });
  const invoices = trpc.invoices.list.useQuery(undefined, { enabled: visible });
  const paymentsExport = trpc.payments.export.useQuery(undefined, { enabled: false });
  const invoicesExport = trpc.invoices.export.useQuery(undefined, { enabled: false });
  const utils = trpc.useUtils();
  const openCash = trpc.cash.open.useMutation({ onSuccess: async (session) => { setFeedback(`Caja #${session.id} abierta.`); setOpeningAmount("0"); await utils.cash.list.invalidate(); }, onError: (error) => setFeedback(error.message) });
  const closeCash = trpc.cash.close.useMutation({ onSuccess: async (session) => { setFeedback(`Caja #${session.id} cerrada.`); setClosingAmount(""); setSessionId("none"); await utils.cash.list.invalidate(); }, onError: (error) => setFeedback(error.message) });
  const collect = trpc.payments.collect.useMutation({ onSuccess: async (result) => { setFeedback(`Cobro registrado. Recibo ${result.receipt.receiptNumber}.`); setShipmentId(""); setAmount(""); setReference(""); await Promise.all([utils.payments.list.invalidate(), utils.cash.list.invalidate()]); }, onError: (error) => setFeedback(error.message) });
  const issueInvoice = trpc.invoices.issue.useMutation({ onSuccess: async (invoice) => { setFeedback(`Factura ${invoice.invoiceNumber} emitida.`); setInvoiceShipmentId(""); setSubtotal(""); setTax("0"); await utils.invoices.list.invalidate(); }, onError: (error) => setFeedback(error.message) });
  const refund = trpc.payments.refund.useMutation({ onSuccess: async (payment) => { setFeedback(`Reembolso registrado para el cobro #${payment.id}.`); setRefundPaymentId(""); setRefundReason(""); setRefundCashSessionId("none"); await Promise.all([utils.payments.list.invalidate(), utils.cash.list.invalidate()]); }, onError: (error) => setFeedback(error.message) });
  if (!visible) return null;
  const id = (value: string) => { const parsed = Number(value); return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined; };
  const validAmount = (value: string) => /^\d+(\.\d{1,2})?$/.test(value);
  const submitOpen = (event: React.FormEvent) => { event.preventDefault(); const selected = id(branchId); if (!selected || !validAmount(openingAmount)) { setFeedback("Selecciona una sucursal y un monto inicial válido."); return; } openCash.mutate({ branchId: selected, openingAmount }); };
  const submitClose = (event: React.FormEvent) => { event.preventDefault(); const selected = id(sessionId); if (!selected || !validAmount(closingAmount)) { setFeedback("Selecciona una caja abierta y un monto final válido."); return; } closeCash.mutate({ sessionId: selected, closingAmount }); };
  const submitPayment = (event: React.FormEvent) => { event.preventDefault(); const shipment = id(shipmentId); if (!shipment || !validAmount(amount) || (method === "cash" && !id(cashSessionId))) { setFeedback("Para cobrar indica envío, monto y caja abierta cuando el método sea efectivo."); return; } collect.mutate({ shipmentId: shipment, amount, method: method as "cash" | "card" | "transfer" | "other", cashSessionId: method === "cash" ? id(cashSessionId) : undefined, reference: reference.trim() || undefined }); };
  const submitInvoice = (event: React.FormEvent) => { event.preventDefault(); const shipment = id(invoiceShipmentId); if (!shipment || !validAmount(subtotal) || !validAmount(tax)) { setFeedback("Indica envío, subtotal e impuesto con montos válidos."); return; } issueInvoice.mutate({ shipmentId: shipment, subtotal, tax }); };
  const submitRefund = (event: React.FormEvent) => { event.preventDefault(); const payment = id(refundPaymentId); if (!payment || refundReason.trim().length < 5) { setFeedback("Indica el cobro y un motivo de reembolso de al menos 5 caracteres."); return; } refund.mutate({ paymentId: payment, reason: refundReason.trim(), cashSessionId: id(refundCashSessionId) }); };
  const downloadJson = (filename: string, data: unknown) => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); };
  const exportPayments = async () => { const result = await paymentsExport.refetch(); if (result.data) downloadJson("gopaq-cobros.json", result.data); else setFeedback("No se pudo exportar cobros; verifica el permiso export."); };
  const exportInvoices = async () => { const result = await invoicesExport.refetch(); if (result.data) downloadJson("gopaq-facturas.json", result.data); else setFeedback("No se pudo exportar facturas; verifica el permiso export."); };
  const openSessions = sessions.data?.filter((session) => session.status === "open") ?? [];
  return <Card className="mt-6 border-0 bg-white shadow-sm"><CardHeader><CardTitle>Cobros, caja y facturación</CardTitle><p className="text-sm text-slate-500">Operación financiera en DOP con recibo numerado y separación por organización y sucursal.</p></CardHeader><CardContent className="space-y-5">
    <div className="grid gap-4 lg:grid-cols-2"><form onSubmit={submitOpen} className="space-y-3 rounded-2xl border border-emerald-100 bg-emerald-50/40 p-4"><p className="text-sm font-bold text-slate-800">Abrir caja</p><div className="grid gap-3 sm:grid-cols-2"><div><Label>Sucursal</Label><Select value={branchId} onValueChange={setBranchId}><SelectTrigger className="mt-1 bg-white"><SelectValue placeholder="Selecciona sucursal" /></SelectTrigger><SelectContent><SelectItem value="none">Selecciona una sucursal</SelectItem>{branches.data?.map((branch) => <SelectItem key={branch.id} value={String(branch.id)}>{branch.name}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="opening-amount">Monto inicial RD$</Label><Input id="opening-amount" value={openingAmount} onChange={(event) => setOpeningAmount(event.target.value)} inputMode="decimal" className="mt-1 bg-white" /></div></div><Button type="submit" disabled={openCash.isPending}>{openCash.isPending ? "Abriendo…" : "Abrir caja"}</Button></form><form onSubmit={submitClose} className="space-y-3 rounded-2xl border border-slate-100 bg-slate-50 p-4"><p className="text-sm font-bold text-slate-800">Cerrar caja</p><div className="grid gap-3 sm:grid-cols-2"><div><Label>Caja abierta</Label><Select value={sessionId} onValueChange={setSessionId}><SelectTrigger className="mt-1 bg-white"><SelectValue placeholder="Selecciona caja" /></SelectTrigger><SelectContent><SelectItem value="none">Selecciona caja abierta</SelectItem>{openSessions.map((session) => <SelectItem key={session.id} value={String(session.id)}>Caja #{session.id} · Sucursal #{session.branchId}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="closing-amount">Monto final RD$</Label><Input id="closing-amount" value={closingAmount} onChange={(event) => setClosingAmount(event.target.value)} inputMode="decimal" className="mt-1 bg-white" /></div></div><Button type="submit" variant="outline" disabled={closeCash.isPending}>{closeCash.isPending ? "Cerrando…" : "Cerrar caja"}</Button></form></div>
    <div className="grid gap-4 lg:grid-cols-2"><form onSubmit={submitPayment} className="space-y-3 rounded-2xl border border-orange-100 bg-orange-50/40 p-4"><p className="text-sm font-bold text-slate-800">Cobro contra entrega</p><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="payment-shipment">ID de envío</Label><Input id="payment-shipment" value={shipmentId} onChange={(event) => setShipmentId(event.target.value)} inputMode="numeric" placeholder="Ej. 1024" className="mt-1 bg-white" /></div><div><Label htmlFor="payment-amount">Monto RD$</Label><Input id="payment-amount" value={amount} onChange={(event) => setAmount(event.target.value)} inputMode="decimal" placeholder="0.00" className="mt-1 bg-white" /></div><div><Label>Método</Label><Select value={method} onValueChange={setMethod}><SelectTrigger className="mt-1 bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="cash">Efectivo</SelectItem><SelectItem value="card">Tarjeta</SelectItem><SelectItem value="transfer">Transferencia</SelectItem><SelectItem value="other">Otro</SelectItem></SelectContent></Select></div><div><Label>Caja para efectivo</Label><Select value={cashSessionId} onValueChange={setCashSessionId}><SelectTrigger className="mt-1 bg-white"><SelectValue placeholder="Solo efectivo" /></SelectTrigger><SelectContent><SelectItem value="none">No aplica</SelectItem>{openSessions.map((session) => <SelectItem key={session.id} value={String(session.id)}>Caja #{session.id}</SelectItem>)}</SelectContent></Select></div></div><div><Label htmlFor="payment-reference">Referencia</Label><Input id="payment-reference" value={reference} onChange={(event) => setReference(event.target.value)} maxLength={160} placeholder="Referencia bancaria o nota" className="mt-1 bg-white" /></div><Button type="submit" disabled={collect.isPending}>{collect.isPending ? "Registrando…" : "Registrar cobro y recibo"}</Button></form><form onSubmit={submitInvoice} className="space-y-3 rounded-2xl border border-blue-100 bg-blue-50/40 p-4"><p className="text-sm font-bold text-slate-800">Emitir factura</p><div className="grid gap-3 sm:grid-cols-3"><div><Label htmlFor="invoice-shipment">ID de envío</Label><Input id="invoice-shipment" value={invoiceShipmentId} onChange={(event) => setInvoiceShipmentId(event.target.value)} inputMode="numeric" className="mt-1 bg-white" /></div><div><Label htmlFor="invoice-subtotal">Subtotal RD$</Label><Input id="invoice-subtotal" value={subtotal} onChange={(event) => setSubtotal(event.target.value)} inputMode="decimal" className="mt-1 bg-white" /></div><div><Label htmlFor="invoice-tax">Impuesto RD$</Label><Input id="invoice-tax" value={tax} onChange={(event) => setTax(event.target.value)} inputMode="decimal" className="mt-1 bg-white" /></div></div><Button type="submit" disabled={issueInvoice.isPending}>{issueInvoice.isPending ? "Emitiendo…" : "Emitir factura"}</Button></form></div>
    <form onSubmit={submitRefund} className="space-y-3 rounded-2xl border border-rose-100 bg-rose-50/40 p-4"><div className="flex items-center gap-2"><RotateCcw className="h-4 w-4 text-rose-600" /><p className="text-sm font-bold text-slate-800">Reembolsar cobro</p></div><div className="grid gap-3 sm:grid-cols-3"><div><Label htmlFor="refund-payment">ID del cobro</Label><Input id="refund-payment" value={refundPaymentId} onChange={(event) => setRefundPaymentId(event.target.value)} inputMode="numeric" placeholder="Ej. 204" className="mt-1 bg-white" /></div><div><Label htmlFor="refund-reason">Motivo</Label><Input id="refund-reason" value={refundReason} onChange={(event) => setRefundReason(event.target.value)} maxLength={500} placeholder="Motivo verificable" className="mt-1 bg-white" /></div><div><Label>Caja para devolución en efectivo</Label><Select value={refundCashSessionId} onValueChange={setRefundCashSessionId}><SelectTrigger className="mt-1 bg-white"><SelectValue placeholder="Solo efectivo" /></SelectTrigger><SelectContent><SelectItem value="none">No aplica</SelectItem>{openSessions.map((session) => <SelectItem key={session.id} value={String(session.id)}>Caja #{session.id}</SelectItem>)}</SelectContent></Select></div></div><Button type="submit" variant="outline" className="border-rose-200 text-rose-700 hover:bg-rose-100" disabled={refund.isPending}>{refund.isPending ? "Procesando…" : "Registrar reembolso"}</Button></form>
    <div className="flex flex-wrap gap-2"><Button variant="outline" className="border-slate-200 bg-white" onClick={() => void exportPayments()} disabled={paymentsExport.isFetching}><Download className="mr-2 h-4 w-4" />{paymentsExport.isFetching ? "Exportando…" : "Exportar cobros"}</Button><Button variant="outline" className="border-slate-200 bg-white" onClick={() => void exportInvoices()} disabled={invoicesExport.isFetching}><Download className="mr-2 h-4 w-4" />{invoicesExport.isFetching ? "Exportando…" : "Exportar facturas"}</Button></div>
    {feedback && <p className="text-sm text-slate-600" role="status">{feedback}</p>}
    <div className="grid gap-4 lg:grid-cols-2"><div><h3 className="mb-2 text-sm font-bold text-slate-800">Cobros recientes</h3>{!payments.isLoading && !payments.data?.length && <p className="rounded-xl border border-dashed border-slate-200 p-4 text-sm text-slate-500">No hay cobros registrados.</p>}{payments.data?.slice(0, 12).map((payment) => <div key={payment.id} className="mb-2 rounded-xl border border-slate-100 bg-slate-50 p-3 text-xs"><p className="font-semibold text-slate-800">Envío #{payment.shipmentId} · {money.format(Number(payment.amount))}</p><p className="mt-1 text-slate-500">{payment.method} · {payment.status} · {payment.currency}</p></div>)}</div><div><h3 className="mb-2 text-sm font-bold text-slate-800">Facturas emitidas</h3>{!invoices.isLoading && !invoices.data?.length && <p className="rounded-xl border border-dashed border-slate-200 p-4 text-sm text-slate-500">No hay facturas emitidas.</p>}{invoices.data?.slice(0, 12).map((invoice) => <div key={invoice.id} className="mb-2 rounded-xl border border-slate-100 bg-slate-50 p-3 text-xs"><p className="font-semibold text-slate-800">{invoice.invoiceNumber} · Envío #{invoice.shipmentId}</p><p className="mt-1 text-slate-500">{money.format(Number(invoice.total))} · {invoice.status} · {invoice.currency}</p></div>)}</div></div>
  </CardContent></Card>;
}
