import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const incidentLabels = { damage: "Daño", address: "Dirección", recipient_unavailable: "Destinatario ausente", customs: "Aduanas", other: "Otra", return_requested: "Devolución solicitada" } as const;
const incidentStatusLabels = { open: "Abierta", investigating: "En investigación", resolved: "Resuelta", returned: "Devuelta" } as const;

export default function IncidentOpsPanel({ visible }: { visible: boolean }) {
  const [shipmentId, setShipmentId] = useState("");
  const [packageId, setPackageId] = useState("");
  const [type, setType] = useState<keyof typeof incidentLabels>("other");
  const [severity, setSeverity] = useState("medium");
  const [description, setDescription] = useState("");
  const [attemptShipmentId, setAttemptShipmentId] = useState("");
  const [routeStopId, setRouteStopId] = useState("");
  const [attemptStatus, setAttemptStatus] = useState("failed");
  const [reason, setReason] = useState("");
  const [attemptNote, setAttemptNote] = useState("");
  const [feedback, setFeedback] = useState("");
  const incidents = trpc.incidents.list.useQuery(undefined, { enabled: visible });
  const attempts = trpc.deliveryAttempts.list.useQuery(undefined, { enabled: visible });
  const utils = trpc.useUtils();
  const createIncident = trpc.incidents.create.useMutation({ onSuccess: async () => { setFeedback("Incidencia registrada y envío marcado para revisión."); setShipmentId(""); setPackageId(""); setDescription(""); await utils.incidents.list.invalidate(); }, onError: (error) => setFeedback(error.message) });
  const resolveIncident = trpc.incidents.resolve.useMutation({ onSuccess: async () => { setFeedback("Incidencia actualizada."); await utils.incidents.list.invalidate(); }, onError: (error) => setFeedback(error.message) });
  const createAttempt = trpc.deliveryAttempts.create.useMutation({ onSuccess: async (attempt) => { setFeedback(`Intento ${attempt.attemptNumber} registrado.`); setAttemptShipmentId(""); setRouteStopId(""); setReason(""); setAttemptNote(""); await utils.deliveryAttempts.list.invalidate(); }, onError: (error) => setFeedback(error.message) });
  if (!visible) return null;
  const positiveId = (value: string) => { const id = Number(value); return Number.isInteger(id) && id > 0 ? id : undefined; };
  const submitIncident = (event: React.FormEvent) => { event.preventDefault(); const id = positiveId(shipmentId); if (!id || description.trim().length < 5) { setFeedback("Indica un envío válido y describe la incidencia."); return; } createIncident.mutate({ shipmentId: id, packageId: positiveId(packageId), type, severity: severity as "low" | "medium" | "high" | "critical", description: description.trim() }); };
  const submitAttempt = (event: React.FormEvent) => { event.preventDefault(); const id = positiveId(attemptShipmentId); if (!id || reason.trim().length < 3) { setFeedback("Indica un envío válido y el motivo del intento."); return; } createAttempt.mutate({ shipmentId: id, routeStopId: positiveId(routeStopId), status: attemptStatus as "failed" | "rescheduled" | "completed", reason: reason.trim(), note: attemptNote.trim() || undefined }); };
  return <Card className="mt-6 border-0 bg-white shadow-sm"><CardHeader><CardTitle>Incidencias, intentos y devoluciones</CardTitle><p className="text-sm text-slate-500">Registra lo ocurrido en campo y conserva la trazabilidad del envío sin sobrescribir eventos previos.</p></CardHeader><CardContent className="space-y-5">
    <div className="grid gap-5 lg:grid-cols-2"><form onSubmit={submitIncident} className="space-y-3 rounded-2xl border border-red-100 bg-red-50/40 p-4"><p className="text-sm font-bold text-slate-800">Nueva incidencia</p><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="incident-shipment">ID de envío</Label><Input id="incident-shipment" inputMode="numeric" value={shipmentId} onChange={(event) => setShipmentId(event.target.value)} placeholder="Ej. 1024" className="mt-1 bg-white" /></div><div><Label htmlFor="incident-package">ID de paquete</Label><Input id="incident-package" inputMode="numeric" value={packageId} onChange={(event) => setPackageId(event.target.value)} placeholder="Opcional" className="mt-1 bg-white" /></div><div><Label>Tipo</Label><Select value={type} onValueChange={(value) => setType(value as keyof typeof incidentLabels)}><SelectTrigger className="mt-1 bg-white"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(incidentLabels).map(([key, label]) => <SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></div><div><Label>Severidad</Label><Select value={severity} onValueChange={setSeverity}><SelectTrigger className="mt-1 bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="low">Baja</SelectItem><SelectItem value="medium">Media</SelectItem><SelectItem value="high">Alta</SelectItem><SelectItem value="critical">Crítica</SelectItem></SelectContent></Select></div></div><div><Label htmlFor="incident-description">Descripción</Label><Input id="incident-description" value={description} onChange={(event) => setDescription(event.target.value)} maxLength={2000} placeholder="Qué ocurrió y cuándo" className="mt-1 bg-white" /></div><Button type="submit" disabled={createIncident.isPending}>{createIncident.isPending ? "Guardando…" : "Registrar incidencia"}</Button></form>
      <form onSubmit={submitAttempt} className="space-y-3 rounded-2xl border border-amber-100 bg-amber-50/40 p-4"><p className="text-sm font-bold text-slate-800">Intento de entrega</p><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="attempt-shipment">ID de envío</Label><Input id="attempt-shipment" inputMode="numeric" value={attemptShipmentId} onChange={(event) => setAttemptShipmentId(event.target.value)} placeholder="Ej. 1024" className="mt-1 bg-white" /></div><div><Label htmlFor="attempt-stop">ID de parada</Label><Input id="attempt-stop" inputMode="numeric" value={routeStopId} onChange={(event) => setRouteStopId(event.target.value)} placeholder="Opcional" className="mt-1 bg-white" /></div><div><Label>Resultado</Label><Select value={attemptStatus} onValueChange={setAttemptStatus}><SelectTrigger className="mt-1 bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="failed">Fallido</SelectItem><SelectItem value="rescheduled">Reprogramado</SelectItem><SelectItem value="completed">Completado</SelectItem></SelectContent></Select></div><div><Label htmlFor="attempt-reason">Motivo</Label><Input id="attempt-reason" value={reason} onChange={(event) => setReason(event.target.value)} maxLength={160} placeholder="No había receptor" className="mt-1 bg-white" /></div></div><div><Label htmlFor="attempt-note">Nota</Label><Input id="attempt-note" value={attemptNote} onChange={(event) => setAttemptNote(event.target.value)} maxLength={1000} placeholder="Detalle de campo" className="mt-1 bg-white" /></div><Button type="submit" disabled={createAttempt.isPending}>{createAttempt.isPending ? "Guardando…" : "Registrar intento"}</Button></form></div>
    {feedback && <p className="text-sm text-slate-600" role="status">{feedback}</p>}
    <div className="grid gap-4 lg:grid-cols-2"><div><h3 className="mb-2 text-sm font-bold text-slate-800">Incidencias abiertas y resueltas</h3>{!incidents.isLoading && !incidents.data?.length && <p className="rounded-xl border border-dashed border-slate-200 p-4 text-sm text-slate-500">No hay incidencias registradas.</p>}{incidents.data?.slice(0, 20).map((item) => <div key={item.id} className="mb-2 rounded-xl border border-slate-100 bg-slate-50 p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm font-semibold">Envío #{item.shipmentId} · {incidentLabels[item.type]}</p><span className="text-xs font-semibold text-orange-700">{incidentStatusLabels[item.status]}</span></div><p className="mt-1 text-xs text-slate-500">{item.description}</p>{["open", "investigating"].includes(item.status) && <div className="mt-2 flex gap-2"><Select defaultValue="investigating" onValueChange={(status) => resolveIncident.mutate({ incidentId: item.id, status: status as "investigating" | "resolved" | "returned" })}><SelectTrigger className="bg-white text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="investigating">Investigar</SelectItem><SelectItem value="resolved">Resolver</SelectItem><SelectItem value="returned">Marcar devuelta</SelectItem></SelectContent></Select></div>}</div>)}</div><div><h3 className="mb-2 text-sm font-bold text-slate-800">Historial de intentos</h3>{!attempts.isLoading && !attempts.data?.length && <p className="rounded-xl border border-dashed border-slate-200 p-4 text-sm text-slate-500">No hay intentos registrados.</p>}{attempts.data?.slice(0, 20).map((item) => <div key={item.id} className="mb-2 rounded-xl border border-slate-100 bg-slate-50 p-3 text-xs"><p className="font-semibold text-slate-800">Envío #{item.shipmentId} · Intento {item.attemptNumber} · {item.status}</p><p className="mt-1 text-slate-500">{item.reason}{item.note ? ` · ${item.note}` : ""}</p></div>)}</div></div>
  </CardContent></Card>;
}
