import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const movementLabels = { received: "Recepción", inspected: "Inspección", putaway: "Ubicación", transfer_out: "Salida a transferencia", transfer_in: "Entrada de transferencia", dispatch: "Despacho", adjustment: "Ajuste" } as const;
const consolidationLabels = { open: "Abierta", sealed: "Sellada", in_transit: "En tránsito", received: "Recibida", reconciled: "Conciliada" } as const;

export default function InventoryTransferPanel({ visible }: { visible: boolean }) {
  const [packageId, setPackageId] = useState("");
  const [warehouseId, setWarehouseId] = useState("none");
  const [movementType, setMovementType] = useState<keyof typeof movementLabels>("received");
  const [fromLocation, setFromLocation] = useState("");
  const [toLocation, setToLocation] = useState("");
  const [note, setNote] = useState("");
  const [fromBranchId, setFromBranchId] = useState("none");
  const [toBranchId, setToBranchId] = useState("none");
  const [consolidationId, setConsolidationId] = useState("");
  const [consolidationPackageId, setConsolidationPackageId] = useState("");
  const [nextStatus, setNextStatus] = useState("sealed");
  const [feedback, setFeedback] = useState("");
  const inventory = trpc.inventory.list.useQuery(undefined, { enabled: visible });
  const consolidations = trpc.consolidations.list.useQuery(undefined, { enabled: visible });
  const warehouses = trpc.warehouses.list.useQuery(undefined, { enabled: visible });
  const branches = trpc.branches.list.useQuery(undefined, { enabled: visible });
  const utils = trpc.useUtils();
  const move = trpc.inventory.move.useMutation({ onSuccess: async () => { setFeedback("Movimiento de inventario registrado."); setPackageId(""); setFromLocation(""); setToLocation(""); setNote(""); await utils.inventory.list.invalidate(); }, onError: (error) => setFeedback(error.message) });
  const create = trpc.consolidations.create.useMutation({ onSuccess: async (result) => { setFeedback(`Consolidación ${result.code} creada.`); await utils.consolidations.list.invalidate(); }, onError: (error) => setFeedback(error.message) });
  const addPackage = trpc.consolidations.addPackage.useMutation({ onSuccess: async () => { setFeedback("Paquete añadido a la consolidación."); setConsolidationPackageId(""); }, onError: (error) => setFeedback(error.message) });
  const advance = trpc.consolidations.advance.useMutation({ onSuccess: async (result) => { setFeedback(`Consolidación actualizada a ${consolidationLabels[result.status]}.`); await utils.consolidations.list.invalidate(); }, onError: (error) => setFeedback(error.message) });

  if (!visible) return null;
  const positiveId = (value: string) => { const id = Number(value); return Number.isInteger(id) && id > 0 ? id : undefined; };
  const recordMove = (event: React.FormEvent) => { event.preventDefault(); const id = positiveId(packageId); if (!id) { setFeedback("Indica un ID de paquete válido."); return; } move.mutate({ packageId: id, warehouseId: warehouseId !== "none" ? positiveId(warehouseId) : undefined, movementType, fromLocation: fromLocation.trim() || undefined, toLocation: toLocation.trim() || undefined, note: note.trim() || undefined }); };
  const createConsolidation = (event: React.FormEvent) => { event.preventDefault(); create.mutate({ fromBranchId: fromBranchId !== "none" ? positiveId(fromBranchId) : undefined, toBranchId: toBranchId !== "none" ? positiveId(toBranchId) : undefined }); };

  return <Card className="mt-6 border-0 bg-white shadow-sm"><CardHeader><CardTitle>Inventario y transferencias con carga</CardTitle><p className="text-sm text-slate-500">Cada movimiento queda asociado a un paquete, almacén y usuario dentro de la organización activa.</p></CardHeader><CardContent className="space-y-5">
    <form onSubmit={recordMove} className="grid gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-4 md:grid-cols-2 lg:grid-cols-4"><div><Label htmlFor="inventory-package">ID del paquete</Label><Input id="inventory-package" inputMode="numeric" value={packageId} onChange={(event) => setPackageId(event.target.value)} placeholder="Ej. 8001" className="mt-1 bg-white" /></div><div><Label>Tipo de movimiento</Label><Select value={movementType} onValueChange={(value) => setMovementType(value as keyof typeof movementLabels)}><SelectTrigger className="mt-1 bg-white"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(movementLabels).map(([key, label]) => <SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></div><div><Label>Almacén</Label><Select value={warehouseId} onValueChange={setWarehouseId}><SelectTrigger className="mt-1 bg-white"><SelectValue placeholder="Sin almacén" /></SelectTrigger><SelectContent><SelectItem value="none">Sin almacén</SelectItem>{warehouses.data?.map((warehouse) => <SelectItem key={warehouse.id} value={String(warehouse.id)}>{warehouse.code} · {warehouse.name}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="inventory-to">Ubicación destino</Label><Input id="inventory-to" value={toLocation} onChange={(event) => setToLocation(event.target.value)} maxLength={80} placeholder="A-01-03" className="mt-1 bg-white" /></div><div><Label htmlFor="inventory-from">Ubicación origen</Label><Input id="inventory-from" value={fromLocation} onChange={(event) => setFromLocation(event.target.value)} maxLength={80} placeholder="B-02-01" className="mt-1 bg-white" /></div><div className="lg:col-span-2"><Label htmlFor="inventory-note">Nota operativa</Label><Input id="inventory-note" value={note} onChange={(event) => setNote(event.target.value)} maxLength={1000} placeholder="Observación de recepción o transferencia" className="mt-1 bg-white" /></div><div className="flex items-end"><Button type="submit" disabled={move.isPending} className="w-full">{move.isPending ? "Registrando…" : "Registrar movimiento"}</Button></div></form>
    <form onSubmit={createConsolidation} className="grid gap-3 rounded-2xl border border-orange-100 bg-orange-50/50 p-4 md:grid-cols-3"><div><Label>Origen</Label><Select value={fromBranchId} onValueChange={setFromBranchId}><SelectTrigger className="mt-1 bg-white"><SelectValue placeholder="Sucursal de origen" /></SelectTrigger><SelectContent><SelectItem value="none">Sin sucursal</SelectItem>{branches.data?.map((branch) => <SelectItem key={branch.id} value={String(branch.id)}>{branch.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Destino</Label><Select value={toBranchId} onValueChange={setToBranchId}><SelectTrigger className="mt-1 bg-white"><SelectValue placeholder="Sucursal de destino" /></SelectTrigger><SelectContent><SelectItem value="none">Sin sucursal</SelectItem>{branches.data?.map((branch) => <SelectItem key={branch.id} value={String(branch.id)}>{branch.name}</SelectItem>)}</SelectContent></Select></div><div className="flex items-end"><Button type="submit" variant="outline" disabled={create.isPending} className="w-full bg-white">{create.isPending ? "Creando…" : "Crear consolidación"}</Button></div></form>
    {feedback && <p className="text-sm text-slate-600" role="status">{feedback}</p>}
    <div className="grid gap-4 lg:grid-cols-2"><div><h3 className="mb-2 text-sm font-bold text-slate-800">Últimos movimientos</h3>{inventory.isLoading && <p className="text-sm text-slate-500">Cargando movimientos…</p>}{!inventory.isLoading && !inventory.data?.length && <p className="rounded-xl border border-dashed border-slate-200 p-4 text-sm text-slate-500">No hay movimientos registrados.</p>}{inventory.data?.slice(0, 12).map((item) => <div key={item.id} className="mb-2 rounded-xl border border-slate-100 bg-slate-50 p-3 text-xs"><p className="font-semibold text-slate-800">Paquete #{item.packageId} · {movementLabels[item.movementType]}</p><p className="mt-1 text-slate-500">{item.fromLocation || "Sin origen"} → {item.toLocation || "Sin destino"}{item.note ? ` · ${item.note}` : ""}</p></div>)}</div><div><h3 className="mb-2 text-sm font-bold text-slate-800">Consolidaciones</h3>{consolidations.isLoading && <p className="text-sm text-slate-500">Cargando consolidaciones…</p>}{!consolidations.isLoading && !consolidations.data?.length && <p className="rounded-xl border border-dashed border-slate-200 p-4 text-sm text-slate-500">No hay consolidaciones creadas.</p>}{consolidations.data?.slice(0, 12).map((item) => <div key={item.id} className="mb-2 rounded-xl border border-slate-100 bg-slate-50 p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm font-semibold text-slate-800">{item.code}</p><span className="rounded-full bg-orange-100 px-2 py-1 text-xs font-semibold text-orange-700">{consolidationLabels[item.status]}</span></div><div className="mt-2 flex flex-col gap-2 sm:flex-row"><Input value={consolidationId === String(item.id) ? consolidationPackageId : ""} onChange={(event) => { setConsolidationId(String(item.id)); setConsolidationPackageId(event.target.value); }} inputMode="numeric" placeholder="ID paquete" className="bg-white text-xs" /><Button variant="outline" size="sm" onClick={() => { const id = positiveId(consolidationPackageId); if (!id) { setFeedback("Indica un ID de paquete válido para cargar."); return; } addPackage.mutate({ consolidationId: item.id, packageId: id }); }} disabled={addPackage.isPending}>Cargar</Button><Select value={consolidationId === String(item.id) ? nextStatus : "sealed"} onValueChange={(value) => { setConsolidationId(String(item.id)); setNextStatus(value); }}><SelectTrigger className="bg-white text-xs sm:w-36"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="sealed">Sellar</SelectItem><SelectItem value="in_transit">Enviar</SelectItem><SelectItem value="received">Recibir</SelectItem><SelectItem value="reconciled">Conciliar</SelectItem></SelectContent></Select><Button size="sm" onClick={() => advance.mutate({ consolidationId: item.id, nextStatus: (consolidationId === String(item.id) ? nextStatus : "sealed") as "sealed" | "in_transit" | "received" | "reconciled" })} disabled={advance.isPending}>Avanzar</Button></div></div>)}</div></div>
  </CardContent></Card>;
}
