import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const stopLabels = { pending: "Pendiente", arrived: "En punto", completed: "Completada", failed: "Fallida", skipped: "Omitida" } as const;

export default function RouteOpsPanel({ visible }: { visible: boolean }) {
  const [routeId, setRouteId] = useState<number | undefined>();
  const [branchId, setBranchId] = useState("none");
  const [vehicleLabel, setVehicleLabel] = useState("");
  const [driverForRoute, setDriverForRoute] = useState<Record<number, string>>({});
  const [stopShipmentId, setStopShipmentId] = useState("");
  const [stopPickupId, setStopPickupId] = useState("");
  const [stopAddress, setStopAddress] = useState("");
  const [barcodeValue, setBarcodeValue] = useState("");
  const [stopStatus, setStopStatus] = useState<Record<number, string>>({});
  const [feedback, setFeedback] = useState("");
  const routes = trpc.routes.list.useQuery(undefined, { enabled: visible });
  const branches = trpc.branches.list.useQuery(undefined, { enabled: visible });
  const drivers = trpc.routes.drivers.useQuery(undefined, { enabled: visible });
  const stops = trpc.routes.stops.useQuery({ routeId: routeId as number }, { enabled: visible && Boolean(routeId) });
  const utils = trpc.useUtils();
  const createRoute = trpc.routes.create.useMutation({ onSuccess: async (route) => { setFeedback(`Ruta ${route.code} creada.`); setVehicleLabel(""); setBranchId("none"); await utils.routes.list.invalidate(); }, onError: (error) => setFeedback(error.message) });
  const assignRoute = trpc.routes.assign.useMutation({ onSuccess: async (route) => { setFeedback(`Ruta ${route.code} asignada al conductor seleccionado.`); await utils.routes.list.invalidate(); }, onError: (error) => setFeedback(error.message) });
  const createStop = trpc.routes.stopsCreate.useMutation({ onSuccess: async (stop) => { setFeedback(`Parada ${stop.sequence} creada.`); setStopShipmentId(""); setStopPickupId(""); setStopAddress(""); await utils.routes.stops.invalidate(); }, onError: (error) => setFeedback(error.message) });
  const updateStop = trpc.routes.stopsUpdate.useMutation({ onSuccess: async () => { setFeedback("Estado de parada actualizado."); await utils.routes.stops.invalidate(); }, onError: (error) => setFeedback(error.message) });
  const scan = trpc.routes.scan.useMutation({ onSuccess: (pkg) => { setFeedback(`Escaneo válido: ${pkg.packageCode}.`); setBarcodeValue(""); }, onError: (error) => setFeedback(error.message) });

  if (!visible) return null;
  const positiveId = (value: string) => { const id = Number(value); return Number.isInteger(id) && id > 0 ? id : undefined; };
  const submitRoute = (event: React.FormEvent) => { event.preventDefault(); setFeedback(""); createRoute.mutate({ branchId: branchId === "none" ? undefined : Number(branchId), vehicleLabel: vehicleLabel.trim() || undefined }); };
  const assignSelected = () => { if (!routeId) return; const driverUserId = Number(driverForRoute[routeId]); if (!driverUserId) { setFeedback("Selecciona un conductor antes de asignar la ruta."); return; } setFeedback(""); assignRoute.mutate({ routeId, driverUserId }); };
  const submitStop = (event: React.FormEvent) => { event.preventDefault(); if (!routeId) return; const shipmentId = positiveId(stopShipmentId); const pickupId = positiveId(stopPickupId); if (!shipmentId && !pickupId) { setFeedback("Vincula la parada a un ID de envío o pickup."); return; } if (shipmentId && pickupId) { setFeedback("Usa un envío o un pickup por parada, no ambos."); return; } if (stopAddress.trim().length < 5) { setFeedback("Indica una dirección real para la parada."); return; } createStop.mutate({ routeId, shipmentId, pickupId, address: stopAddress.trim() }); };
  const saveStopStatus = (stopId: number) => { const status = stopStatus[stopId]; if (!status) { setFeedback("Selecciona un estado de parada."); return; } updateStop.mutate({ stopId, status: status as "pending" | "arrived" | "completed" | "failed" | "skipped" }); };
  const submitScan = (event: React.FormEvent) => { event.preventDefault(); if (!barcodeValue.trim()) { setFeedback("Introduce el código de barras escaneado."); return; } scan.mutate({ barcodeValue: barcodeValue.trim(), routeId }); };

  return <Card className="mt-6 border-0 bg-white shadow-sm"><CardHeader><CardTitle>Rutas, paradas y escaneo</CardTitle><p className="text-sm text-slate-500">Crea recorridos, asigna conductores y valida paquetes mediante códigos ligados a la ruta.</p></CardHeader><CardContent className="space-y-5">
    <form onSubmit={submitRoute} className="grid gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-4 md:grid-cols-[1fr_1fr_auto] md:items-end"><div><Label htmlFor="route-branch">Sucursal de salida</Label><Select value={branchId} onValueChange={setBranchId}><SelectTrigger id="route-branch" className="mt-1 bg-white"><SelectValue placeholder="Selecciona una sucursal" /></SelectTrigger><SelectContent><SelectItem value="none">Sin sucursal asignada</SelectItem>{branches.data?.map((branch) => <SelectItem key={branch.id} value={String(branch.id)}>{branch.name} · {branch.city}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="route-vehicle">Vehículo o referencia</Label><Input id="route-vehicle" value={vehicleLabel} onChange={(event) => setVehicleLabel(event.target.value)} maxLength={100} placeholder="Opcional" className="mt-1 bg-white" /></div><Button type="submit" disabled={createRoute.isPending}>{createRoute.isPending ? "Creando…" : "Crear ruta"}</Button></form>
    {feedback && <p className="text-sm text-slate-600" role="status">{feedback}</p>}
    {routes.isLoading && <p className="text-sm text-slate-500">Cargando rutas…</p>}
    {!routes.isLoading && !routes.data?.length && <div className="rounded-2xl border border-dashed border-slate-200 p-5 text-center text-sm text-slate-500">No hay rutas operativas registradas.</div>}
    <div className="grid gap-2">{routes.data?.slice(0, 20).map((route) => <button key={route.id} type="button" onClick={() => setRouteId(route.id)} className={`flex items-center justify-between rounded-xl border p-3 text-left transition ${route.id === routeId ? "border-orange-300 bg-orange-50" : "border-slate-100 bg-slate-50 hover:border-orange-200"}`}><span><strong className="block text-sm">{route.code}</strong><span className="text-xs text-slate-500">{route.status} · {route.vehicleLabel || "Vehículo por asignar"} · {route.driverUserId ? `Conductor #${route.driverUserId}` : "Sin conductor"}</span></span><span className="text-xs font-semibold text-orange-600">Ver paradas</span></button>)}</div>
    {routeId && <div className="space-y-4 border-t border-slate-100 pt-4"><div className="flex flex-col gap-3 rounded-2xl bg-orange-50 p-4 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0 flex-1"><Label htmlFor="route-driver">Conductor de la ruta #{routeId}</Label><Select value={driverForRoute[routeId] || "none"} onValueChange={(value) => setDriverForRoute((current) => ({ ...current, [routeId]: value }))}><SelectTrigger id="route-driver" className="mt-1 bg-white"><SelectValue placeholder="Selecciona un conductor" /></SelectTrigger><SelectContent><SelectItem value="none">Sin conductor</SelectItem>{drivers.data?.map((driver) => <SelectItem key={driver.userId} value={String(driver.userId)}>{driver.name || driver.email || `Usuario #${driver.userId}`}</SelectItem>)}</SelectContent></Select></div><Button onClick={assignSelected} disabled={assignRoute.isPending || !drivers.data?.length}>{assignRoute.isPending ? "Asignando…" : "Asignar conductor"}</Button></div>
      <form onSubmit={submitScan} className="grid gap-2 rounded-2xl border border-slate-100 bg-slate-50 p-4 sm:grid-cols-[1fr_auto] sm:items-end"><div><Label htmlFor="route-barcode">Escaneo de código de barras</Label><Input id="route-barcode" value={barcodeValue} onChange={(event) => setBarcodeValue(event.target.value)} maxLength={120} placeholder="Introduce el valor leído por el escáner" className="mt-1 bg-white" /></div><Button type="submit" disabled={scan.isPending}>{scan.isPending ? "Validando…" : "Validar escaneo"}</Button></form>
      <form onSubmit={submitStop} className="grid gap-2 rounded-2xl border border-slate-100 bg-slate-50 p-4 md:grid-cols-3"><div><Label htmlFor="stop-shipment">ID de envío</Label><Input id="stop-shipment" inputMode="numeric" value={stopShipmentId} onChange={(event) => setStopShipmentId(event.target.value)} placeholder="Opcional" className="mt-1 bg-white" /></div><div><Label htmlFor="stop-pickup">ID de pickup</Label><Input id="stop-pickup" inputMode="numeric" value={stopPickupId} onChange={(event) => setStopPickupId(event.target.value)} placeholder="Opcional" className="mt-1 bg-white" /></div><div><Label htmlFor="stop-address">Dirección</Label><Input id="stop-address" value={stopAddress} onChange={(event) => setStopAddress(event.target.value)} maxLength={1000} placeholder="Dirección de entrega o recogida" className="mt-1 bg-white" /></div><div className="md:col-span-3"><Button type="submit" disabled={createStop.isPending}>{createStop.isPending ? "Creando…" : "Añadir parada"}</Button></div></form>
      <div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-orange-600">Paradas de la ruta #{routeId}</p>{stops.isLoading && <p className="text-sm text-slate-500">Cargando paradas…</p>}{!stops.isLoading && !stops.data?.length && <p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-500">No hay paradas registradas para esta ruta.</p>}<div className="space-y-2">{stops.data?.map((stop) => <div key={stop.id} className="flex flex-col gap-2 rounded-lg bg-slate-50 p-3 text-xs sm:flex-row sm:items-center sm:justify-between"><span><strong>{stop.sequence}. {stop.address}</strong><span className="ml-2 text-slate-500">{stop.shipmentId ? `Envío #${stop.shipmentId}` : `Pickup #${stop.pickupId}`}</span></span><div className="flex gap-2"><Select value={stopStatus[stop.id] || "current"} onValueChange={(value) => setStopStatus((current) => ({ ...current, [stop.id]: value }))}><SelectTrigger className="w-36 bg-white"><SelectValue placeholder={stopLabels[stop.status]} /></SelectTrigger><SelectContent><SelectItem value="current">{stopLabels[stop.status]}</SelectItem>{Object.entries(stopLabels).filter(([key]) => key !== stop.status).map(([key, label]) => <SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select><Button variant="outline" size="sm" onClick={() => saveStopStatus(stop.id)} disabled={updateStop.isPending}>Guardar</Button></div></div>)}</div></div>
    </div>}
  </CardContent></Card>;
}
