import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const initialForm = { serviceType: "national" as const, senderName: "", recipientName: "", originAddress: "", destinationAddress: "", originCountry: "DO", destinationCountry: "DO", estimatedAmount: "" };

type FormState = typeof initialForm;

export default function ShipmentListPanel({ visible }: { visible: boolean }) {
  const shipments = trpc.logistics.shipments.list.useQuery(undefined, { enabled: visible });
  const [form, setForm] = useState<FormState>(initialForm);
  const [feedback, setFeedback] = useState("");
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editRecipient, setEditRecipient] = useState("");
  const [editDestination, setEditDestination] = useState("");
  const create = trpc.logistics.shipments.create.useMutation({ onSuccess: () => { setForm(initialForm); setFeedback("Envío creado correctamente."); void shipments.refetch(); }, onError: (error) => setFeedback(error.message) });
  const edit = trpc.logistics.shipments.update.useMutation({ onSuccess: () => { setEditingId(null); setFeedback("Envío actualizado correctamente."); void shipments.refetch(); }, onError: (error) => setFeedback(error.message) });

  if (!visible) return null;
  const updateForm = (key: keyof FormState, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); setFeedback(""); create.mutate({ ...form, estimatedAmount: form.estimatedAmount || undefined }); };
  const startEdit = (shipment: NonNullable<typeof shipments.data>[number]) => { setEditingId(shipment.id); setEditRecipient(shipment.recipientName); setEditDestination(shipment.destinationAddress); setFeedback(""); };
  const submitEdit = (event: React.FormEvent) => { event.preventDefault(); if (editingId === null) return; edit.mutate({ id: editingId, recipientName: editRecipient, destinationAddress: editDestination }); };

  return <Card className="mt-6 border-0 bg-white shadow-sm"><CardHeader><CardTitle>Envíos</CardTitle><p className="text-sm text-slate-500">Registros reales aislados por organización. Los códigos de rastreo se generan en el servidor.</p></CardHeader><CardContent className="space-y-6">
    <form onSubmit={submit} className="grid gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-4 md:grid-cols-2"><div className="md:col-span-2"><p className="text-sm font-semibold text-slate-900">Crear envío</p><p className="text-xs text-slate-500">Completa los datos mínimos del remitente, destinatario y ruta.</p></div><div><Label htmlFor="sender-name">Remitente</Label><Input id="sender-name" value={form.senderName} onChange={(event) => updateForm("senderName", event.target.value)} required minLength={2} maxLength={180} /></div><div><Label htmlFor="recipient-name">Destinatario</Label><Input id="recipient-name" value={form.recipientName} onChange={(event) => updateForm("recipientName", event.target.value)} required minLength={2} maxLength={180} /></div><div><Label htmlFor="origin-address">Dirección de origen</Label><Input id="origin-address" value={form.originAddress} onChange={(event) => updateForm("originAddress", event.target.value)} required minLength={5} maxLength={1000} /></div><div><Label htmlFor="destination-address">Dirección de destino</Label><Input id="destination-address" value={form.destinationAddress} onChange={(event) => updateForm("destinationAddress", event.target.value)} required minLength={5} maxLength={1000} /></div><div><Label>Servicio</Label><Select value={form.serviceType} onValueChange={(value) => updateForm("serviceType", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="local">Local</SelectItem><SelectItem value="national">Nacional</SelectItem><SelectItem value="international">Internacional</SelectItem><SelectItem value="assisted_purchase">Compra asistida</SelectItem><SelectItem value="heavy_cargo">Carga pesada</SelectItem></SelectContent></Select></div><div><Label htmlFor="estimated-amount">Monto estimado (RD$)</Label><Input id="estimated-amount" inputMode="decimal" placeholder="Opcional" value={form.estimatedAmount} onChange={(event) => updateForm("estimatedAmount", event.target.value)} pattern="^\\d+(\\.\\d{1,2})?$" /></div><div className="md:col-span-2 flex items-center gap-3"><Button type="submit" disabled={create.isPending}>{create.isPending ? "Guardando…" : "Crear envío"}</Button>{feedback && <p className="text-sm text-slate-600" role="status">{feedback}</p>}</div></form>
    {editingId !== null && <form onSubmit={submitEdit} className="grid gap-3 rounded-2xl border border-orange-100 bg-orange-50 p-4 md:grid-cols-2"><div className="md:col-span-2"><p className="text-sm font-semibold text-orange-950">Editar envío #{editingId}</p><p className="text-xs text-orange-800">Solo se pueden editar envíos en estado comercial borrador o cotizado.</p></div><div><Label htmlFor="edit-recipient">Destinatario</Label><Input id="edit-recipient" value={editRecipient} onChange={(event) => setEditRecipient(event.target.value)} required minLength={2} maxLength={180} /></div><div><Label htmlFor="edit-destination">Dirección de destino</Label><Input id="edit-destination" value={editDestination} onChange={(event) => setEditDestination(event.target.value)} required minLength={5} maxLength={1000} /></div><div className="flex gap-2 md:col-span-2"><Button type="submit" disabled={edit.isPending}>{edit.isPending ? "Actualizando…" : "Guardar cambios"}</Button><Button type="button" variant="outline" onClick={() => setEditingId(null)}>Cancelar</Button></div></form>}
    <div className="space-y-2">{shipments.isLoading ? <p className="text-sm text-slate-500">Cargando envíos…</p> : shipments.data?.length ? shipments.data.slice(0, 8).map((shipment) => <div key={shipment.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><div><strong className="block text-sm text-slate-900">{shipment.trackingCode}</strong><span className="text-xs text-slate-500">{shipment.senderName} → {shipment.recipientName} · {shipment.originCountry} → {shipment.destinationCountry} · {shipment.serviceType}</span></div><div className="flex items-center gap-2"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{shipment.physicalStatus}</span>{["draft", "quoted"].includes(shipment.commercialStatus) && <Button variant="outline" size="sm" onClick={() => startEdit(shipment)}>Editar</Button>}</div></div>) : <p className="text-sm text-slate-500">Aún no hay envíos registrados en esta organización.</p>}</div>
  </CardContent></Card>;
}
